import type { Metadata } from "next";
import Link from "next/link";
import styles from "../corporate.module.css";

export const metadata: Metadata={title:"Remote Eye V3 | NULLWORKS",description:"Remote Eye V3 is a NULLWORKS bounded remote-observation and inspection architecture preserving source truth and human authority.",alternates:{canonical:"https://nullworks.systems/remote-eye-v3"}};

export default function RemoteEyePage(){return <main className={styles.page}><div className={styles.shell}>
<nav className={styles.nav}><Link className={styles.brand} href="/">NULLWORKS<span>OI SUITE · WORKING SYSTEM</span></Link><div className={styles.mono}>REMOTE EYE V3</div></nav>
<section className={styles.compactHero}><div className={styles.eyebrow}>REMOTE OBSERVATION + INSPECTION</div><h1 className={styles.title}>Move the eyes without surrendering the source truth.</h1><p className={styles.lead}>Remote Eye V3 explores a bounded inspection console in which a remote camera or observation source can extend a human operator into a physical environment while preserving the original source, separating observation from interpretation, and keeping consequential authority human.</p><div className={styles.actions}><Link className={styles.primary} href="/japan">Japan program</Link><Link className={styles.secondary} href="/architecture">OI SUITe architecture</Link></div></section>
<section className={styles.section}><div className={styles.sectionHeader}><div className={styles.kicker}>WHAT THE SYSTEM TESTS</div><h2 className={styles.h2}>Remote perception is useful only if the evidence survives the interface.</h2><p className={styles.body}>A camera feed can become operationally dangerous when annotation, AI interpretation, compression, stale imagery, or interface state is mistaken for the source itself. Remote Eye treats the source frame as evidence first. Derived observations can assist the operator, but they do not silently overwrite what the sensor actually captured.</p></div><div className={styles.list}><div className={styles.item}><strong>Source truth preserved</strong><span>Original observation remains distinguishable from overlays, notes, machine interpretation, and later conclusions.</span></div><div className={styles.item}><strong>Frozen source frame</strong><span>An operator can preserve the exact visual state used for an observation instead of relying on memory of a moving feed.</span></div><div className={styles.item}><strong>Bounded machine assistance</strong><span>AI or computer vision can help inspect, compare, describe, or route evidence without being granted invisible authority over the underlying source.</span></div><div className={styles.item}><strong>Human authority final</strong><span>The system can extend perception and reduce distance. It does not convert an uncertain machine observation into an automatic consequential decision.</span></div></div></section>
<section className={styles.section}><div className={styles.statement}><strong>WORKING SYSTEM · EXPERIMENTAL FIELD BUILD</strong><p>Remote Eye V3 is evidence of a working experimental interface and operating pattern, not a claim of a finished universal robot, certified inspection product, or production autonomous system. Its value is the architecture: preserve evidence, expose uncertainty, bound machine capability, and keep the operator able to reconstruct what happened.</p></div></section>
<section className={styles.section}><div className={styles.sectionHeader}><div className={styles.kicker}>JAPAN CO-DEVELOPMENT FIT</div><h2 className={styles.h2}>Inspection, maintenance, emergency response, robotics, and machine vision.</h2><p className={styles.body}>A Japanese partner could supply the environment and the hard constraint: a location difficult to enter, an inspection workflow that loses evidence, a maintenance task requiring remote expertise, or a robotic camera platform. NULLWORKS can then test the governed observation layer around that real problem rather than designing a generic robot in isolation.</p></div></section>
<footer className={styles.footer}><span>NULLWORKS · REMOTE EYE V3 · WORKING SYSTEM</span><Link className={styles.route} href="/japan">Return to Japan program →</Link></footer>
</div></main>}
