import { createHash, randomUUID } from "node:crypto";

type ScoreInput = { playerName?: unknown; venue?: unknown; score?: unknown; badHits?: unknown; friendlyHits?: unknown; misses?: unknown; roundSeconds?: unknown; playedAt?: unknown; clientId?: unknown };
type ScoreRow = { receipt:string; player_name:string; venue:string; score:number; bad_hits:number; friendly_hits:number; misses:number; round_seconds:number; played_at:string; created_at:string };

class AlienZapperError extends Error { constructor(public code:string,message:string,public status=400,public detail?:unknown){super(message)} }
function config(){const url=(process.env.ALIEN_ZAPPER_SUPABASE_URL||process.env.FOREST_SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL||"").replace(/\/$/,"");const key=process.env.ALIEN_ZAPPER_SUPABASE_SERVICE_ROLE_KEY||process.env.FOREST_SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY||"";const salt=process.env.ALIEN_ZAPPER_HASH_SALT||process.env.FOREST_HASH_SALT||"";return{url,key,salt,configured:Boolean(url&&key&&salt)}}
function requireConfig(){const c=config();if(!c.configured)throw new AlienZapperError("STORAGE_NOT_CONFIGURED","The global Alien Zapper leaderboard is not connected yet. The score may still be saved locally on the phone.",503);return c}
async function rest<T>(path:string,init:RequestInit={}){const c=requireConfig();const r=await fetch(`${c.url}/rest/v1/${path}`,{...init,cache:"no-store",headers:{apikey:c.key,Authorization:`Bearer ${c.key}`,"Content-Type":"application/json",...init.headers}});const text=await r.text();let body:any=null;try{body=text?JSON.parse(text):null}catch{body=text}if(!r.ok)throw new AlienZapperError("STORAGE_REQUEST_FAILED",body?.message||`Leaderboard storage failed with HTTP ${r.status}.`,r.status,body);return body as T}
const clean=(v:unknown,n:number)=>typeof v==="string"?v.replace(/\u0000/g,"").trim().slice(0,n):"";
function validate(i:ScoreInput){const playerName=clean(i.playerName,20).replace(/[^A-Za-z0-9 _-]/g,"");const venue=clean(i.venue,60);const score=Math.floor(Number(i.score));const badHits=Math.floor(Number(i.badHits));const friendlyHits=Math.floor(Number(i.friendlyHits));const misses=Math.floor(Number(i.misses));const roundSeconds=Math.floor(Number(i.roundSeconds));if(playerName.length<2)throw new AlienZapperError("INVALID_PLAYER","Player name must be 2–20 simple characters.");if(!Number.isFinite(score)||score<0||score>100000)throw new AlienZapperError("INVALID_SCORE","Score is outside the accepted range.");for(const [k,v] of Object.entries({badHits,friendlyHits,misses}))if(!Number.isFinite(v)||v<0||v>1000)throw new AlienZapperError("INVALID_STATS",`${k} is invalid.`);if(![30,45,60,90].includes(roundSeconds))throw new AlienZapperError("INVALID_ROUND","Unsupported round length.");return{playerName,venue:venue||"NULLWORKS Halloween 2026",score,badHits,friendlyHits,misses,roundSeconds,clientId:clean(i.clientId,80)}}
function actorHash(request:Request){const c=requireConfig();const ip=request.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||"unknown";const ua=request.headers.get("user-agent")||"unknown";return createHash("sha256").update(`${c.salt}|${ip}|${ua}`).digest("hex")}
async function rateLimit(hash:string){const since=new Date(Date.now()-10*60*1000).toISOString();const q=new URLSearchParams({select:"receipt",actor_hash:`eq.${hash}`,created_at:`gte.${since}`,limit:"7"});const rows=await rest<any[]>(`alien_zapper_scores?${q}`);if(rows.length>=6)throw new AlienZapperError("RATE_LIMITED","This device has submitted several scores recently. Please wait a few minutes.",429)}
export async function saveAlienScore(request:Request,input:ScoreInput){const v=validate(input),hash=actorHash(request);await rateLimit(hash);const receipt=`NW-AZ-${new Date().toISOString().replace(/[-:.TZ]/g,"").slice(0,14)}-${randomUUID().slice(0,8).toUpperCase()}`;const row={receipt,player_name:v.playerName,venue:v.venue,score:v.score,bad_hits:v.badHits,friendly_hits:v.friendlyHits,misses:v.misses,round_seconds:v.roundSeconds,played_at:new Date().toISOString(),actor_hash:hash,payload:{client_id:v.clientId||null,game_version:"ALIEN_ZAPPER_1.0",camera_only:true}};const rows=await rest<ScoreRow[]>("alien_zapper_scores",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(row)});return rows[0]}
export async function listAlienScores(limit=50){const q=new URLSearchParams({select:"receipt,player_name,venue,score,bad_hits,friendly_hits,misses,round_seconds,played_at,created_at",order:"score.desc,played_at.asc",limit:String(Math.max(1,Math.min(100,limit)))});return rest<ScoreRow[]>(`alien_zapper_scores?${q}`)}
export async function alienZapperStatus(){const c=config();if(!c.configured)return{state:"STORAGE_NOT_CONFIGURED",configured:false,reachable:false};try{await rest<any[]>("alien_zapper_scores?select=receipt&limit=1");return{state:"READY",configured:true,reachable:true}}catch(e){return{state:"STORAGE_UNREACHABLE",configured:true,reachable:false,detail:e instanceof Error?e.message:"Unknown error"}}}
export function alienZapperErrorResponse(e:unknown){const x=e instanceof AlienZapperError?e:new AlienZapperError("INTERNAL_ERROR",e instanceof Error?e.message:"Unknown error",500);return Response.json({ok:false,error:{code:x.code,message:x.message,detail:x.detail}},{status:x.status,headers:{"Cache-Control":"no-store"}})}
