const ALBUM_ART="https://i.ytimg.com/vi/J2ZUIL68X-Y/maxresdefault.jpg";
const practices = [
  ["Observe", "Notice the small changes before they become large problems."],
  ["Record", "Preserve the story, source, context, uncertainty, and failed paths."],
  ["Protect the why", "Keep the human judgment behind the final repair or decision."],
  ["Pass it forward", "Route the lesson to future people without turning it into unverified doctrine."],
];

export default function MrSlothPage() {
  return (
    <main>
      <style>{`
        *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#efe5d1;color:#211812}a{color:inherit}.page{min-height:100vh;background:#f2e6cf;font-family:Arial,'Hiragino Kaku Gothic ProN','Yu Gothic',sans-serif}.shell{width:min(1040px,100%);margin:auto;padding:0 22px}
        .nav{height:78px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #9d7b53;background:#2d241d;color:#fff7e6;padding:0 18px;margin:0 -22px}.brand{font-family:Georgia,'Yu Mincho',serif;font-size:24px;font-weight:700;letter-spacing:.14em;text-decoration:none}.brand small{display:block;font-family:Arial,sans-serif;font-size:10px;letter-spacing:.2em;color:#d7a85f;margin-top:4px}.lang{border:1px solid #d7a85f;padding:10px 16px;text-decoration:none;border-radius:999px;font-size:13px;font-weight:800;background:#fff5df;color:#2d241d;min-width:108px;text-align:center}
        .hero{display:grid;grid-template-columns:1fr .95fr;gap:46px;align-items:center;padding:58px 0 66px;border-bottom:1px solid #a88c65}.label{font-size:11px;font-weight:900;letter-spacing:.18em;color:#9b2f24;text-transform:uppercase}.hero h1,h2,h3{font-family:Georgia,'Yu Mincho',serif;font-weight:600;letter-spacing:-.035em;color:#241a14}.hero h1{font-size:clamp(52px,8vw,90px);line-height:.92;margin:18px 0 22px}.hero h1 span{display:block;font-size:.38em;color:#6a4c2f;letter-spacing:.04em;margin-top:14px}.lead{font-family:Georgia,'Yu Mincho',serif;font-size:clamp(28px,4vw,42px);line-height:1.25;margin:0 0 22px;color:#2d241d}.copy{font-size:17px;line-height:1.88;color:#4f4135}.heroArt{margin:0;background:#2b211a;border:8px solid #fff6e7;outline:1px solid #8d6a43;box-shadow:0 20px 45px rgba(61,42,25,.22)}.heroArt img{display:block;width:100%;height:auto;aspect-ratio:1/1;object-fit:cover}
        .actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:28px}.button{display:inline-flex;padding:13px 16px;text-decoration:none;font-size:12px;font-weight:900;letter-spacing:.04em;text-transform:uppercase;border-radius:3px}.primary{background:#a52d22;color:#fff8eb}.secondary{border:1px solid #775432;background:#f8edda;color:#2b2018}
        section{padding:58px 0;border-bottom:1px solid #a88c65}h2{font-size:clamp(38px,6vw,64px);line-height:1.04;margin:14px 0 24px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:16px;margin-top:28px}.card{background:#fff7e8;border:1px solid #b79b72;padding:24px}.card strong{display:block;font-family:Georgia,'Yu Mincho',serif;font-size:25px;color:#5f3a24;margin-bottom:10px}.card p{margin:0;line-height:1.75;color:#4e4035}
        .demo{background:#493225;color:#fff6e5;padding:36px;border-left:6px solid #b64031}.demo h3{font-size:34px;margin:0 0 18px;color:#fff9eb}.demo p,.demo li{color:#f6e8d2;line-height:1.8}.demo ul{padding-left:20px}.demo li{margin:10px 0}
        .media{background:#2d241d;color:#fff8e8;padding:28px;border:1px solid #6f543b}.mediaIntro{display:grid;grid-template-columns:.78fr 1.22fr;gap:26px;align-items:center}.cover{width:100%;display:block;border:7px solid #efe1c8}.media h3{font-size:34px;margin:0 0 12px;color:#fff8e8}.media p{color:#f2e4cd;line-height:1.8}.playerTitle{font-size:12px;font-weight:900;letter-spacing:.16em;text-transform:uppercase;color:#d9aa62;margin:28px 0 10px}.youtube{position:relative;width:100%;aspect-ratio:16/9;overflow:hidden;background:#120f0d}.youtube iframe,.spotify iframe{position:absolute;inset:0;width:100%;height:100%;border:0}.spotify{position:relative;height:352px;border-radius:12px;overflow:hidden}.streamLink{display:inline-block;margin-top:18px;color:#fff3d4;font-weight:800;text-underline-offset:5px}
        .quote{background:#c69b57;padding:34px;font-family:Georgia,'Yu Mincho',serif;font-size:clamp(30px,5vw,50px);line-height:1.2;color:#231b14}.contact{display:grid;grid-template-columns:1fr 1fr;gap:14px}.contact a{background:#fff7e8;border:1px solid #b79b72;padding:18px;text-decoration:none;font-weight:800;color:#432d20}.status{display:inline-block;border:1px solid #8e7657;background:#fff7e8;padding:12px 16px;border-radius:999px;font-weight:800;color:#2f241c}.footer{padding:34px 0 60px;color:#625344;font-size:13px;line-height:1.7}
        @media(max-width:760px){.shell{padding:0 16px}.nav{height:68px;margin:0 -16px;padding:0 14px}.brand{font-size:19px}.lang{min-width:102px;padding:9px 12px}.hero{grid-template-columns:1fr;padding:38px 0 46px;gap:26px}.hero h1{font-size:54px}.copy{font-size:16px}.grid,.mediaIntro,.contact{grid-template-columns:1fr}section{padding:44px 0}.heroArt{border-width:6px}.media{padding:20px}.media h3{font-size:29px}h2{font-size:39px}.demo{padding:25px 20px}.spotify{height:352px}}
      `}</style>
      <div className="page"><div className="shell">
        <nav className="nav"><a className="brand" href="/mr-sloth">KIKIGAKI<small>聞き書き</small></a><a className="lang" href="/jp/mr-sloth" aria-label="View Japanese version">日本語</a></nav>
        <header className="hero"><div><div className="label">Cultural demonstration // First observer</div><h1>KIKIGAKI<span>聞き書き</span></h1><p className="lead">Preserving what work forgets.</p><p className="copy">A craftsmanship-first educational project preserving small frontline observations, failed paths, practical judgment, uncertainty, and the reasons behind a repair before they disappear.</p><p className="copy"><strong>Created independently by NULLWORKS as a cultural demonstration inspired by craftsmanship, oral history, and continuous improvement. Offered respectfully for public learning and evaluation.</strong></p><div className="actions"><a className="button primary" href="#demonstration">Explore the demonstration</a><a className="button secondary" href="#music">Hear the project</a></div></div><figure className="heroArt"><img src={ALBUM_ART} alt="KIKIGAKI album artwork showing Mr. Sloth recording observations" /></figure></header>
        <section id="story"><div className="label">01 // The problem</div><h2>The final repair survives. The human lesson often does not.</h2><p className="copy">Someone notices a weak signal. The team follows a false lead. A workaround emerges. The problem is finally solved. The official record keeps the completed action—but may lose the clue, hesitation, failed diagnosis, production pressure, and human judgment that made the solution possible.</p></section>
        <section><div className="label">02 // The observer</div><h2>Slow enough to notice what fast systems miss.</h2><p className="copy">ナマケモノ氏 — Mr. Sloth — is KIKIGAKI's first observer and learning companion. He makes a serious operational problem approachable without turning human stories into verified fact, approved procedure, or automated policy.</p><div className="grid">{practices.map(([t,b])=><div className="card" key={t}><strong>{t}</strong><p>{b}</p></div>)}</div></section>
        <section id="demonstration"><div className="label">03 // Woven City educational demonstration</div><h2>Mobility of information begins with preserving context.</h2><div className="demo"><h3>A public cultural and educational demonstration</h3><p>KIKIGAKI is being submitted for consideration through Toyota Woven City's Inventors route. It explores whether practical field knowledge can move safely between people, shifts, disciplines, and generations without losing provenance or promoting uncertainty into fact.</p><ul><li>Bilingual English and Japanese public experience</li><li>Craftsmanship and frontline knowledge preservation</li><li>Human-centered Operational Intelligence governance</li><li>Original artwork, character, video, and Japanese music</li><li>No request for endorsement, affiliation, adoption, or commercial commitment</li></ul></div></section>
        <section id="music"><div className="label">04 // Hear the project</div><h2>消える前に</h2><div className="media"><div className="mediaIntro"><img className="cover" src={ALBUM_ART} alt="Before It Disappears album artwork"/><div><h3>消える前に<br/>Kieru Mae ni<br/>Before It Disappears</h3><p>The first official release by 聞き書き / KIKIGAKI. A quiet musical artifact preserving voices, doubt, pain, and hard-earned wisdom for someone not yet met.</p></div></div><div className="playerTitle">Watch and listen</div><div className="youtube"><iframe src="https://www.youtube.com/embed/J2ZUIL68X-Y" title="Before It Disappears by KIKIGAKI" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen loading="lazy"></iframe></div><div className="playerTitle">Official release on Spotify</div><div className="spotify"><iframe src="https://open.spotify.com/embed/track/35kT4K5f4LZzy0OBymRUaL?utm_source=generator&theme=0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy" title="Before It Disappears on Spotify"></iframe></div><a className="streamLink" href="https://distrokid.com/hyperfollow/kikigaki/-kieru-mae-ni-before-it-disappears/" target="_blank" rel="noreferrer">View all streaming services →</a></div></section>
        <section><div className="label">05 // Open invitation</div><h2>Offered for evaluation, not adoption.</h2><p className="copy">KIKIGAKI is an independent cultural and educational project published by NULLWORKS Research. Toyota, Woven by Toyota, and Woven City have not accepted, adopted, endorsed, partnered with, or affiliated with this project. The current request is simply to evaluate whether the idea is useful and where it may best belong.</p></section>
        <section><div className="quote">Observe. Record. Preserve the why. Pass it forward.</div></section>
        <section><div className="label">06 // Connect</div><h2>A quiet project. An open invitation.</h2><div className="contact"><a href="https://www.instagram.com/operational_observer/" target="_blank" rel="noreferrer">Instagram<br/>@operational_observer</a><a href="mailto:operational.observer@gmail.com">Email<br/>operational.observer@gmail.com</a></div><p className="copy" style={{marginTop:24}}>Published by NULLWORKS Research, Arizona, USA.</p><div className="status">WOVEN CITY INVENTORS DEMONSTRATION // PREPARING SUBMISSION</div></section>
        <footer className="footer">聞き書き / KIKIGAKI — Preserving what work forgets.<br/>Observe. Record. Preserve. Pass it forward.</footer>
      </div></div>
    </main>
  );
}
