"use client";
import {useState} from "react";
type View="global"|"control"|"standard"|"evidence"|"audit"|"public";
type Drawer={title:string;kicker:string;body:string;items:string[]}|null;
const markets=[
 {name:"Japan",code:"JP / JPY",signal:"INTERVENTION RISK",rate:"1.00%",ref:"USD/JPY 157.50",use:"Regional productivity + execution confidence"},
 {name:"Switzerland",code:"CH / CHF",signal:"FUNDING ROTATION",rate:"0.00%",ref:"CHF/JPY 196.00",use:"Cross-border capital provenance"},
 {name:"Reconstruction",code:"MULTI / FX",signal:"DELIVERY RISK",rate:"MULTI",ref:"BASKET CONTROL",use:"Donor-to-outcome accountability"}
];
const gates=[
 ["01","Authorize mandate","Public authority","verified","7 proofs","¥148.0M"],
 ["02","Prove procurement","Independent reviewer","verified","12 proofs","¥72.4M"],
 ["03","Test delivery","Site operator","review","8 proofs","¥31.8M"],
 ["04","Reconstruct decision","Auditor","pending","0 proofs","—"],
 ["05","Revitalize region","Community partner","pending","0 proofs","—"]
];
const vdcs=[
 ["VCDS-01","Authority","Identity, mandate, jurisdiction and spending ceiling"],
 ["VCDS-02","Conditions","Release rules, milestones, conflicts and stop conditions"],
 ["VCDS-03","Evidence","Protected source records with fingerprints and signatures"],
 ["VCDS-04","Decision","Human approvals, dissent, overrides and timestamps"],
 ["VCDS-05","Outcome","Measured delivery, regional value and beneficiary proof"],
 ["VCDS-06","Disclosure","Minimum public proof without protected-data leakage"]
];
const records=[
 ["Capital mandate","AUTHORITY","7F2A...91D0","Public Authority","SEALED"],
 ["Procurement decision","PROCUREMENT","A441...03CC","Independent Reviewer","SEALED"],
 ["Delivery invoice","INVOICE","903E...B17A","Regional Vendor","VERIFIED"],
 ["Site evidence bundle","FIELD PROOF","2C80...9A04","Site Operator","REVIEW"],
 ["FX assumption v2","RISK DECISION","C117...EE28","Finance Controller","SEALED"]
];
export default function Home(){const[view,setView]=useState<View>("global"),[market,setMarket]=useState(0),[gate,setGate]=useState(2),[toast,setToast]=useState(""),[drawer,setDrawer]=useState<Drawer>(null);const ping=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2200)};return <main className="kintsugi">
 <header><div className="brand"><span>金</span><div>NULLWORKS <b>{"// KINTSUGI GLOBAL"}</b><small>VERIFIABLE CAPITAL DEPLOYMENT INFRASTRUCTURE</small></div></div><div className="security"><i/> HUMAN AUTHORITY ACTIVE</div></header>
 <section className="hero"><div><p className="eyebrow">VCDS // GLOBAL CONTROL PLANE</p><h1>Institutional confidence,<br/><em>made verifiable.</em></h1><p>KINTSUGI governs how capital is authorized, evidenced, reviewed and translated into productive outcomes—especially when currencies, markets and political conditions are unstable.</p></div><aside><small>OPERATING DOCTRINE</small><strong>We do not defend currencies.</strong><span>We help institutions remain credible through volatility.</span></aside></section>
 <nav>{([['global','Global Signals'],['control','Capital Control'],['standard','VCDS Standard'],['evidence','Evidence Vault'],['audit','Audit Replay'],['public','Public Proof']] as [View,string][]).map(([v,l])=><button className={view===v?'active':''} onClick={()=>setView(v)} key={v}>{l}</button>)}</nav>
 <div className="synthetic">SYNTHETIC DATA // DEMONSTRATION ONLY</div>
 {view==="global"&&<Global market={market} setMarket={setMarket} ping={ping}/>} {view==="control"&&<Control gate={gate} setGate={setGate} open={setDrawer}/>} {view==="standard"&&<Standard open={setDrawer}/>} {view==="evidence"&&<Evidence ping={ping}/>} {view==="audit"&&<Audit/>} {view==="public"&&<Public/>}
 <footer><span>Protected records stay private.</span><span>Proofs make decisions verifiable.</span><span>Humans remain in command.</span></footer>{toast&&<div className="toast">{toast}</div>}{drawer&&<DetailDrawer data={drawer} close={()=>setDrawer(null)}/>} 
 </main>}
function Top({global=false}:{global?:boolean}){return <section className="top panel"><div><p className="eyebrow">{global?'GLOBAL MANDATE':'JAPAN LIGHTHOUSE // SYNTHETIC PILOT'}</p><h2>{global?'Capital integrity across borders':'Beppu Thermal Works'}</h2><span>{global?'Currency-neutral governance for public, private and blended finance.':'Vacant ryokan → geothermal workshop + remote operations hub'}</span></div><div className="seal"><b>{global?'VCDS':'2/5'}</b><small>{global?'v0.1 / TEST':'VERIFIED'}</small></div></section>}
function Global({market,setMarket,ping}:{market:number;setMarket:(n:number)=>void;ping:(s:string)=>void}){const m=markets[market];return <div className="workspace"><Top global/><section className="orientation panel"><b>What am I looking at?</b><span>Select a risk environment, inspect the institutional roles, then follow the five-stage proof chain from capital authorization to measured regional outcomes.</span></section><section className="market-tabs">{markets.map((x,i)=><button className={market===i?'selected':''} onClick={()=>setMarket(i)} key={x.name}><small>{x.code}</small><b>{x.name}</b><span>{x.signal}</span></button>)}</section><section className="split"><article className="panel card"><div className="card-head"><div><p>SELECTED ENVIRONMENT</p><h3>{m.name}</h3></div><em>{m.signal}</em></div><div className="duo"><div><small>POLICY RATE</small><b>{m.rate}</b></div><div><small>MARKET REFERENCE</small><b>{m.ref}</b></div></div><p className="application"><small>KINTSUGI APPLICATION</small>{m.use}</p><button className="primary" onClick={()=>ping(`${m.name} control packet opened`)}>Open control packet <span>→</span></button></article><article className="panel card"><div className="card-head"><div><p>SEPARATION OF POWERS</p><h3>Who does what</h3></div><em>6 ROLES</em></div>{[["Government","Sets lawful mandate"],["Bank","Custodies and settles"],["Investor","Commits risk capital"],["Operator","Delivers the work"],["Auditor","Verifies evidence"],["KINTSUGI","Preserves the chain"]].map((x,i)=><div className="actor" key={x[0]}><i>{String(i+1).padStart(2,'0')}</i><b>{x[0]}</b><span>{x[1]}</span></div>)}</article></section><section className="panel flow">{["AUTHORIZE","PROVE","TEST","RECONSTRUCT","REVITALIZE"].map((x,i)=><div key={x}><b>{x}</b><span>{["Mandate + ceiling","Evidence + identity","Delivery + controls","Independent replay","Measured outcomes"][i]}</span></div>)}</section></div>}
function Control({gate,setGate,open}:{gate:number;setGate:(n:number)=>void;open:(d:Drawer)=>void}){const g=gates[gate];return <div className="workspace"><Top/><section className="metrics">{[["AUTHORIZED","¥148.0M","Signed mandate"],["DEPLOYED","¥72.4M","48.9% verified"],["LOCAL VALUE","¥31.8M","7 regional vendors"],["EVIDENCE HEALTH","94.2","2 reviews required"]].map(x=><article className="panel metric" key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><span>{x[2]}</span></article>)}</section><section className="split"><article className="panel card"><div className="card-head"><div><p>HUMAN-GOVERNED LOOP</p><h3>Capital gates</h3></div><em>NO AUTONOMOUS RELEASE</em></div>{gates.map((x,i)=><button className={`gate ${gate===i?'selected':''}`} onClick={()=>setGate(i)} key={x[0]}><i className={x[3]}>{x[3]==='verified'?'✓':x[3]==='review'?'!':'·'}</i><span><b>{x[0]} / {x[1]}</b><small>{x[2]}</small></span><em>{x[4]}</em></button>)}</article><article className="panel card"><div className="card-head"><div><p>SELECTED GATE</p><h3>{g[1]}</h3></div><em>{g[3]}</em></div><div className="details"><div><small>AUTHORITY</small><b>{g[2]}</b></div><div><small>CAPITAL</small><b>{g[5]}</b></div><div><small>PROOF BUNDLE</small><b>{g[4]}</b></div><div><small>CONTROL</small><b>VCDS-{g[0]}</b></div></div><p className="human"><b>Human gate</b> Two authorized signatures required. AI may surface risk; it cannot release capital.</p><button className="primary" onClick={()=>open({kicker:`VCDS-${g[0]} // SYNTHETIC PACKET`,title:g[1],body:`Review the evidence and authority chain before this gate may advance. Current state: ${g[3]}.`,items:[`Authority: ${g[2]}`,`Capital scope: ${g[5]}`,`Evidence bundle: ${g[4]}`,"Required: project owner signature","Required: independent reviewer signature"]})}>Open review packet <span>→</span></button></article></section><Outcomes/></div>}
function Standard({open}:{open:(d:Drawer)=>void}){return <div className="workspace"><section className="intro panel"><p className="eyebrow">VERIFIABLE CAPITAL DEPLOYMENT STANDARD // v0.1</p><h2>A shared grammar for trustworthy execution.</h2><span>Six control objects make a capital decision independently reconstructable without publishing every protected record.</span></section><section className="standard">{vdcs.map((x,i)=><button className="panel" onClick={()=>open({kicker:`${x[0]} // TEST SPECIFICATION`,title:x[1],body:x[2],items:["Required fields defined","Human authority identified","Evidence fingerprint required","Disclosure boundary recorded","Independent replay supported"]})} key={x[0]}><i>{i+1}</i><span><small>{x[0]}</small><b>{x[1]}</b><em>{x[2]}</em></span><strong>→</strong></button>)}</section><Boundary/></div>}
function Evidence({ping}:{ping:(s:string)=>void}){return <div className="workspace"><section className="panel card"><div className="card-head"><div><p>PROTECTED EVIDENCE</p><h3>Evidence vault</h3></div><button onClick={()=>ping('Synthetic intake opened')}>+ ADD EVIDENCE</button></div><p className="privacy"><b>PRIVATE BY DEFAULT.</b> Source files stay protected. Approved fingerprints, signatures and metadata enter the proof rail.</p><div className="records">{records.map(r=><button key={r[2]} onClick={()=>ping(`${r[0]} integrity verified`)}><span><b>{r[0]}</b><small>{r[1]}</small></span><code>{r[2]}</code><span>{r[3]}</span><em>{r[4]}</em></button>)}</div></section></div>}
function Audit(){return <div className="workspace"><section className="panel card"><div className="card-head"><div><p>INDEPENDENT RECONSTRUCTION</p><h3>Decision replay · 14 August 2026</h3></div><em>CHAIN INTACT</em></div>{[["08:42","Mandate sealed","Public Authority"],["09:16","Risk assumption approved","Finance Controller"],["10:03","Procurement countersigned","Independent Reviewer"],["13:28","Invoice matched","KINTSUGI Control"],["15:47","Field evidence submitted","Site Operator"]].map((x,i)=><div className="event" key={x[0]}><i>{i+1}</i><time>{x[0]}</time><span><b>{x[1]}</b><small>{x[2]}</small></span></div>)}<p className="ok"><b>✓ Decision trail reconstructed</b> Required signatures, evidence fingerprints and authority transitions are present. No protected document was disclosed.</p></section></div>}
function Public(){return <div className="workspace public"><span>PUBLIC PROOF // VERIFIED SYNTHETIC PILOT</span><h2>Beppu Thermal Works</h2><p>Authorized regional capital translated into a geothermal systems workshop and remote operations hub.</p><div className="proof"><b>✓ Proof bundle intact</b><small>Last verified 14 Aug 2026 · 15:47 JST</small></div><Outcomes/><Boundary/></div>}
function Outcomes(){return <section className="panel outcomes"><div className="card-head"><div><p>PRODUCTIVE CAPACITY</p><h3>Regional outcomes</h3></div><em>BASELINE → VERIFIED</em></div><div>{[["1","property reused"],["14","jobs committed"],["620h","labor saved / month"],["18%","energy intensity ↓"],["¥31.8M","local procurement"]].map(x=><article key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></article>)}</div></section>}
function Boundary(){return <section className="panel boundary"><div><small>KINTSUGI DOES</small><b>Govern evidence, authority, milestones and disclosure.</b></div><div><small>KINTSUGI DOES NOT</small><b>Set monetary policy, promise returns or autonomously move public money.</b></div></section>}
function DetailDrawer({data,close}:{data:NonNullable<Drawer>;close:()=>void}){return <div className="drawer-backdrop" onClick={close}><section className="drawer" onClick={e=>e.stopPropagation()} role="dialog" aria-modal="true" aria-label={data.title}><button className="drawer-close" onClick={close} aria-label="Close detail">×</button><p className="eyebrow">{data.kicker}</p><h2>{data.title}</h2><p>{data.body}</p><div>{data.items.map(x=><span key={x}><i>✓</i>{x}</span>)}</div><button className="primary" onClick={close}>Return to control room <b>→</b></button></section></div>}
