const ALBUM_ART="https://i.ytimg.com/vi/J2ZUIL68X-Y/maxresdefault.jpg";
const practices = [
  ["観察する", "大きな問題になる前に、小さな変化に気づく。"],
  ["記録する", "言葉だけでなく、背景、迷い、不確実性、失敗した道も残す。"],
  ["なぜを守る", "最終的な修理や判断の背後にある人間の知恵を保存する。"],
  ["未来へ渡す", "不確かな話を事実や規則に変えず、必要な人へ学びを届ける。"],
];

export default function Page() {
  return (
    <main>
      <style>{`
        *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#ead4a8;color:#211812}a{color:inherit}.page{min-height:100vh;background:linear-gradient(180deg,#f3e5c7 0%,#e7c98f 100%);font-family:Arial,'Hiragino Kaku Gothic ProN','Yu Gothic',sans-serif}.shell{width:min(1040px,100%);margin:auto;padding:0 22px}
        .nav{height:78px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #8c6335;background:#d4a154;color:#251a12;padding:0 18px;margin:0 -22px}.brand{font-family:Georgia,'Yu Mincho',serif;font-size:24px;font-weight:700;letter-spacing:.12em;text-decoration:none}.brand small{display:block;font-family:Arial,sans-serif;font-size:10px;letter-spacing:.2em;color:#7f241c;margin-top:4px}.lang{border:1px solid #3a281b;padding:10px 16px;text-decoration:none;border-radius:999px;font-size:13px;font-weight:900;background:#fff3d8;color:#2d2118;min-width:108px;text-align:center}
        .hero{display:grid;grid-template-columns:1fr .95fr;gap:46px;align-items:center;padding:58px 0 66px;border-bottom:1px solid #9b7548}.label{font-size:11px;font-weight:900;letter-spacing:.18em;color:#972c22;text-transform:uppercase}.hero h1,h2,h3{font-family:Georgia,'Yu Mincho',serif;font-weight:600;letter-spacing:-.035em;color:#241a14}.hero h1{font-size:clamp(52px,8vw,90px);line-height:.92;margin:18px 0 22px}.hero h1 span{display:block;font-size:.38em;color:#6a4027;letter-spacing:.04em;margin-top:14px}.lead{font-family:Georgia,'Yu Mincho',serif;font-size:clamp(28px,4vw,42px);line-height:1.35;margin:0 0 22px;color:#2d241d}.copy{font-size:17px;line-height:1.95;color:#403228}.albumFrame{margin:0;aspect-ratio:1/1;overflow:hidden;background:#d8ac67;border:8px solid #fff1d3;outline:1px solid #80592f;box-shadow:0 18px 38px rgba(78,48,20,.22)}.albumFrame img{display:block;width:100%;height:100%;object-fit:cover;object-position:center top;transform:scale(1.34);transform-origin:50% 0}
        .actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:28px}.button{display:inline-flex;padding:13px 16px;text-decoration:none;font-size:12px;font-weight:900;letter-spacing:.04em;text-transform:uppercase;border-radius:3px}.primary{background:#a52d22;color:#fff8eb}.secondary{border:1px solid #6a4727;background:#f8e5bd;color:#2b2018}
        section{padding:58px 0;border-bottom:1px solid #9b7548}h2{font-size:clamp(38px,6vw,64px);line-height:1.08;margin:14px 0 24px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:16px;margin-top:28px}.card{background:#f7e4bd;border:1px solid #a77c47;padding:24px}.card strong{display:block;font-family:Georgia,'Yu Mincho',serif;font-size:25px;color:#562f1d;margin-bottom:10px}.card p{margin:0;line-height:1.8;color:#3f3127}
        .demo,.media{background:#d6a65f;color:#24180f;padding:32px;border:1px solid #8f622f}.demo{border-left:6px solid #a52d22}.demo h3,.media h3,.demo h3 *,.media h3 *{font-size:34px;margin:0 0 18px;color:#24180f!important}.demo p,.demo p *,.demo li,.demo li *,.media p,.media p *{color:#342519!important;line-height:1.9}.demo ul{padding-left:20px}.demo li{margin:10px 0}.mediaIntro{display:grid;grid-template-columns:.78fr 1.22fr;gap:26px;align-items:center}.playerTitle{font-size:12px;font-weight:900;letter-spacing:.16em;text-transform:uppercase;color:#6d241b;margin:28px 0 10px}.youtube{position:relative;width:100%;aspect-ratio:16/9;overflow:hidden;background:#120f0d}.youtube iframe,.spotify iframe{position:absolute;inset:0;width:100%;height:100%;border:0}.spotify{position:relative;height:352px;border-radius:12px;overflow:hidden}.streamLink,.streamLink *{display:inline-block;margin-top:18px;color:#2b1d13!important;font-weight:900;text-underline-offset:5px}
        .quote{background:#c99542;padding:34px;font-family:Georgia,'Yu Mincho',serif;font-size:clamp(30px,5vw,50px);line-height:1.25;color:#23170e}.contact{display:grid;grid-template-columns:1fr 1fr;gap:14px}.contact a{background:#f7e4bd;border:1px solid #a77c47;padding:18px;text-decoration:none;font-weight:800;color:#432d20}.status{display:inline-block;border:1px solid #79532f;background:#f7e4bd;padding:12px 16px;border-radius:999px;font-weight:900;color:#2f241c}.footer{padding:34px 0 60px;color:#4b392b;font-size:13px;line-height:1.7}
        @media(max-width:760px){.shell{padding:0 16px}.nav{height:68px;margin:0 -16px;padding:0 14px}.brand{font-size:19px}.lang{min-width:102px;padding:9px 12px}.hero{grid-template-columns:1fr;padding:38px 0 46px;gap:26px}.hero h1{font-size:54px}.copy{font-size:16px}.grid,.mediaIntro,.contact{grid-template-columns:1fr}section{padding:44px 0}.albumFrame{border-width:6px}.demo,.media{padding:22px}.media h3,.media h3 *,.demo h3,.demo h3 *{font-size:29px}h2{font-size:39px}.spotify{height:352px}}
      `}</style>
      <div className="page"><div className="shell">
        <nav className="nav"><a className="brand" href="/jp/mr-sloth">聞き書き<small>KIKIGAKI</small></a><a className="lang" href="/mr-sloth" aria-label="英語版を見る">English</a></nav>
        <header className="hero"><div><div className="label">文化・教育デモンストレーション // 最初の観測者</div><h1>聞き書き<span>KIKIGAKI</span></h1><p className="lead">現場が忘れてしまうものを、消える前に残す。</p><p className="copy">小さな兆候、熟練者の判断、失敗した道、不確実性、そして「なぜそうしたのか」。聞き書きは、仕事の中で生まれた知恵を文脈ごと未来へ渡す、ものづくりを起点とした独立した教育・文化プロジェクトです。</p><p className="copy"><strong>ものづくり、聞き書き、継続的改善への敬意から、NULLWORKS が独立して制作した文化デモンストレーションです。公共の学びと評価のために、謙虚に公開しています。</strong></p><div className="actions"><a className="button primary" href="#demonstration">デモンストレーションを見る</a><a className="button secondary" href="#music">作品を聴く</a></div></div><figure className="albumFrame"><img src={ALBUM_ART} alt="ナマケモノ氏が静かな作業机で記録している聞き書きのアートワーク" /></figure></header>
        <section id="story"><div className="label">01 // 課題</div><h2>最後の修理は残る。人間の学びは、しばしば消えていく。</h2><p className="copy">誰かが小さな異変に気づく。間違った仮説を試す。現場で一時的な工夫が生まれる。やがて問題は解決する。しかし正式な記録には最終的な作業だけが残り、手がかり、迷い、失敗、現場の圧力、判断の理由が失われることがあります。</p></section>
        <section><div className="label">02 // ナマケモノ氏</div><h2>ゆっくりだから、速い仕組みが見落とすものに気づける。</h2><p className="copy">ナマケモノ氏は、聞き書きの最初の観測者であり、学びの伴走者です。人間の経験を親しみやすく伝えながら、語られた内容を確認済みの事実、承認された手順、自動化された規則へ勝手に変えることはありません。</p><div className="grid">{practices.map(([t,b])=><div className="card" key={t}><strong>{t}</strong><p>{b}</p></div>)}</div></section>
        <section id="demonstration"><div className="label">03 // Woven City 教育デモンストレーション</div><h2>情報のモビリティは、文脈を守ることから始まる。</h2><div className="demo"><h3>公開型の文化・教育デモンストレーション</h3><p>聞き書きは、Toyota Woven City の Inventors 窓口へ検討用として提出されました。現場知を、人、シフト、専門分野、世代の間で移動させる際に、出所と不確実性を失わず、物語を事実へ格上げしない方法を探ります。</p><ul><li>英語・日本語のバイリンガル公開体験</li><li>ものづくりと現場知の保存</li><li>人間中心の Operational Intelligence ガバナンス</li><li>オリジナルのアート、キャラクター、映像、日本語楽曲</li><li>採用、提携、承認、商業的関係を求める提案ではありません</li></ul></div></section>
        <section id="music"><div className="label">04 // 作品を聴く</div><h2>消える前に</h2><div className="media"><div className="mediaIntro"><figure className="albumFrame"><img src={ALBUM_ART} alt="消える前に アートワーク"/></figure><div><h3>消える前に<br/>Kieru Mae ni<br/>Before It Disappears</h3><p>聞き書き / KIKIGAKI の最初の公式リリース。現場の声、迷い、痛み、そして長い経験から生まれた知恵を、まだ会っていない誰かのために残す歌です。</p></div></div><div className="playerTitle">映像と音楽</div><div className="youtube"><iframe src="https://www.youtube.com/embed/J2ZUIL68X-Y" title="聞き書き 消える前に" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen loading="lazy"></iframe></div><div className="playerTitle">Spotify 公式リリース</div><div className="spotify"><iframe src="https://open.spotify.com/embed/track/35kT4K5f4LZzy0OBymRUaL?utm_source=generator&theme=0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy" title="Spotifyで消える前にを聴く"></iframe></div><a className="streamLink" href="https://distrokid.com/hyperfollow/kikigaki/-kieru-mae-ni-before-it-disappears/" target="_blank" rel="noreferrer">すべての配信サービスを見る →</a></div></section>
        <section><div className="label">05 // 開かれた招待</div><h2>採用ではなく、評価と対話のために。</h2><p className="copy">聞き書きは、NULLWORKS Research が発行する独立した文化・教育プロジェクトです。Toyota、Woven by Toyota、Woven City が本プロジェクトを採用、承認、提携、後援している事実はありません。今回の提出は、この考え方に価値があるか、そしてどこに最も適しているかを評価していただくためのものです。</p></section>
        <section><div className="quote">観察する。記録する。なぜを守る。未来へ渡す。</div></section>
        <section><div className="label">06 // つながる</div><h2>静かなプロジェクト。開かれた招待。</h2><div className="contact"><a href="https://www.instagram.com/operational_observer/" target="_blank" rel="noreferrer">Instagram<br/>@operational_observer</a><a href="mailto:operational.observer@gmail.com">Email<br/>operational.observer@gmail.com</a></div><p className="copy" style={{marginTop:24}}>発行：NULLWORKS Research · Arizona, USA.</p><div className="status">WOVEN CITY INVENTORS デモンストレーション // 検討用として提出済み</div></section>
        <footer className="footer">聞き書き / KIKIGAKI — Preserving what work forgets.<br/>観察する。記録する。保存する。未来へ渡す。</footer>
      </div></div>
    </main>
  );
}
