const cards=[
["観察する","大きな問題になる前に、小さな変化に気づく。"],
["記録する","物語、文脈、不確実性、そして情報源を残す。"],
["保存する","学びが失われないように、『なぜ』を保管する。"],
["伝える","未来の人と仕組みを守るために、学びを渡す。"]
];
export default function Page(){return <main><style>{`
*{box-sizing:border-box}body{margin:0;background:#f3efe4;color:#182027}a{color:inherit}.shell{width:min(900px,100%);margin:auto;padding:0 24px}.nav{height:72px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #cfc4b2}.brand{font-weight:900;letter-spacing:.12em;text-decoration:none}.brand span,.label{color:#8f1f18}.lang{border:1px solid #1e3a50;padding:9px 12px;text-decoration:none;border-radius:999px}.hero,section{padding:62px 0;border-bottom:1px solid #cfc4b2}.label{font-size:12px;font-weight:900;letter-spacing:.18em}.hero h1,h2{font-family:Georgia,'Yu Mincho',serif;font-weight:600;letter-spacing:-.04em}.hero h1{font-size:clamp(58px,10vw,104px);line-height:.9;margin:18px 0}.hero h1 span{display:block;color:#1e3a50;font-size:.42em;letter-spacing:.02em;margin-top:16px}.lead{font-family:Georgia,'Yu Mincho',serif;font-size:clamp(26px,4vw,40px);line-height:1.35}.copy{font-size:18px;line-height:1.9;color:#59656c}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:16px;margin-top:28px}.card{background:#fbf8f0;border:1px solid #cfc3ad;padding:24px}.card strong{display:block;font-family:Georgia,'Yu Mincho',serif;font-size:25px;color:#1e3a50;margin-bottom:10px}.card p{margin:0;line-height:1.75;color:#5d696f}.letter{background:#1e3a50;color:#f7f1e7;padding:38px}.letter h3{font-family:Georgia,'Yu Mincho',serif;font-size:34px;margin:0 0 18px}.letter p{font-size:18px;line-height:1.9;color:#e2e6e8}.quote{background:#c7a36a;padding:32px;font-family:Georgia,'Yu Mincho',serif;font-size:clamp(30px,5vw,52px);line-height:1.25}.status{display:inline-block;border:1px solid #b8aa92;background:#fbf8f0;padding:12px 16px;border-radius:999px;font-weight:800}.footer{padding:32px 0 60px;color:#788289;font-size:13px}@media(max-width:700px){.shell{padding:0 16px}.hero,section{padding:44px 0}.hero h1{font-size:58px}.copy{font-size:16px}.grid{grid-template-columns:1fr}.letter{padding:26px}}
`}</style><div className="shell"><nav className="nav"><a className="brand" href="/"><span>NW</span> NULLWORKS</a><a className="lang" href="/mr-sloth">English</a></nav><header className="hero"><div className="label">前線観測者 // 日本向けギフト版</div><h1>ナマケモノ氏<span>Mr. Sloth</span></h1><p className="lead">消えてしまう前に、現場の学びを残す。</p><p className="copy">小さな兆候に気づき、現場で得た知恵を守り、知識が失われる前に文脈ごと残すための、静かな教育キャラクターです。</p></header><section><div className="label">01 // 物語</div><h2>仕組み、人、そして大切な学びを静かに見つめる。</h2><p className="copy">ナマケモノ氏は、NULLWORKSの実験中に偶然生まれました。その失敗を捨てるのではなく、どこで役に立つのかを考えました。情報源、不確実性、文脈を保ったまま残せば、偶然の発見にも教育的な価値がある。そのことを思い出させる存在です。</p></section><section><div className="label">02 // 使命</div><h2>見落とされるものを、未来へ残す。</h2><div className="grid">{cards.map(([t,b])=><div className="card" key={t}><strong>{t}</strong><p>{b}</p></div>)}</div></section><section><div className="label">03 // なぜ日本か</div><h2>ものづくり、謙虚さ、継続的な改善。</h2><p className="copy">日本のものづくり、丁寧な観察、継続的改善の文化に敬意を払い、この教育的ギフトを考えました。最初の候補はWoven Cityですが、採用、提携、承認を示すものではありません。</p></section><section><div className="label">04 // 敬意を込めた贈り物</div><h2>採用を求めず、自由にお届けします。</h2><div className="letter"><h3>日本の皆さまへ</h3><p>現場で最も価値のある学びは、静かに発見され、問題が解決したあとに忘れられてしまうことがあります。</p><p>ナマケモノ氏が、知識を謙虚に丁寧に残すことについて、たった一つでも新しい会話を生むなら、それだけで十分です。</p><p>これは教育的な贈り物として、敬意を込めて無償でご提案するものです。採用、提携、承認を求めるものではありません。</p></div></section><section><div className="quote">速い仕組みが見落とすものに、気づけるほどゆっくり。</div></section><section><div className="label">05 // 現在の状態</div><h2>一度に、一人の相手へ、敬意を持って。</h2><p className="copy">提案資料を整え、最もふさわしい一人へ届け、返答または所定の無返答期間を記録します。その後、次の候補へ丁寧に進みます。一斉送信、提携の暗示、架空の完了報告は行いません。</p><div className="status">WOVEN CITY 候補 // 未連絡</div></section><footer className="footer">NULLWORKS · ナマケモノ氏 · 教育的ギフト提案 · 最終判断は人間にあります。</footer></div></main>}
