import AnvilShell from "../AnvilShell";
import ArtistCard from "../ArtistCard";
import { projects } from "../catalog";

const ARTIST_SLUGS = ["9-volt","blood-pagoda","penny","nan-violence","nan-wisdom","non-opera-italica","swiss-doom-opera","mountain-lords","harescramble","silt-serpent","limestone-kin"];

export default function Page(){
  const artists=projects.filter(p=>ARTIST_SLUGS.includes(p.slug));
  return <AnvilShell><style>{`.idx{width:min(1180px,calc(100% - 32px));margin:auto;padding:70px 0}.idx h1{font-size:clamp(65px,12vw,150px);line-height:.8;letter-spacing:-.07em;margin:0 0 25px}.idx>p{max-width:760px;color:#aaa49a;font-size:21px;line-height:1.6}.cards{display:grid;grid-template-columns:repeat(2,1fr);gap:12px;margin-top:45px}.card{border:1px solid #302e29;border-radius:24px;padding:25px;text-decoration:none;background:#0a0a09;color:#eee9df;display:block}.card b{font:900 10px ui-monospace,monospace;color:var(--accent);letter-spacing:.12em}.card h2{font-size:clamp(34px,5vw,62px);line-height:.9;letter-spacing:-.05em;margin:14px 0}.card p{color:#9f9a91;line-height:1.55}.cardHit{display:block;width:100%;background:transparent;border:0;padding:0;color:inherit;text-align:left;cursor:pointer;font:inherit}.dropCue{display:inline-block;margin-top:16px;color:var(--accent);font:900 10px ui-monospace,monospace;letter-spacing:.12em}.albumList{margin-top:16px;border-top:1px solid #302e29;padding-top:8px}.albumRow{display:block;padding:12px 0;border-bottom:1px solid #262522;text-decoration:none;color:#eee9df}.albumRow:last-child{border-bottom:0}.albumRow strong{display:block;font-size:18px;letter-spacing:-.03em}.albumRow span{display:block;margin-top:4px;color:#9f9a91;font-size:13px;line-height:1.4}.albumRow:hover strong{color:var(--accent)}@media(max-width:700px){.cards{grid-template-columns:1fr}}`}</style><section className="idx"><h1>ARTISTS</h1><p>Separate identities, shared infrastructure. ANVIL preserves the contract of each performer instead of sanding everything into one house style. Artists with more than one album open a cycle list instead of jumping to a single page.</p><div className="cards">{artists.map(p=><ArtistCard key={p.slug} project={p}/>)}</div></section></AnvilShell>}
