export const paperPart02 = `<p>This requirement also prevents maximum-context dumping from masquerading as continuity. Context must be relevant, fresh enough for the use, and authorized for the receiver. A packet that exposes every historical detail may violate privacy, overwhelm the worker, and increase the probability that irrelevant context steers the decision. Continuity is minimum sufficient context under consequence and authority, not total recall.</p>
<h3>2.4 The Minimum Continuity Envelope</h3>
<p>The full Continuity Packet is a constitutional model. The Minimum Continuity Envelope is a provisional implementation pattern: the smallest governed decision record sufficient for a future authorized observer to identify the decision, recover its material basis, understand the authorized state transition, and know when review is required. Its depth should scale with consequence, reversibility, novelty, uncertainty, recurrence, and the number of downstream dependencies.</p>
<div class="tableWrap"><table><tbody><tr><th>Field</th><th>Question answered</th><th>When required</th></tr><tr><td>Decision identity and version</td><td>Which bounded decision is this?</td><td>Always</td></tr><tr><td>Actor or system identity</td><td>Who or what produced it?</td><td>Always</td></tr><tr><td>Authority and jurisdiction</td><td>Why could this actor decide or act?</td><td>Always for state change</td></tr><tr><td>Evidence references and classes</td><td>What supported the conclusion?</td><td>Always for consequential decisions</td></tr><tr><td>Material assumptions</td><td>What had to be true for the decision to fit?</td><td>When assumptions affect outcome</td></tr><tr><td>Rationale and alternatives</td><td>Why this action rather than another?</td><td>Scaled to consequence and novelty</td></tr><tr><td>Before-state and intended after-state</td><td>What was expected to change?</td><td>For operational actions</td></tr><tr><td>Completion definition</td><td>What observable condition counts as done?</td><td>For executable work</td></tr><tr><td>Uncertainty and dissent</td><td>What remained unknown or contested?</td><td>When material</td></tr><tr><td>Counterfactual boundary</td><td>What would reasonably have changed the choice?</td><td>For medium/high consequence</td></tr><tr><td>Reconsideration trigger</td><td>What future change requires review?</td><td>For state-dependent or long-lived decisions</td></tr><tr><td>Verification and receipt</td><td>What evidence shows the action and outcome?</td><td>For all completed consequential actions</td></tr><tr><td>Retention and disclosure class</td><td>How long and to whom may it remain available?</td><td>When data or rights are sensitive</td></tr></tbody></table></div>
<h3>2.5 Proportionality</h3>
<p>A coffee preference and a safety shutdown should not carry identical documentation. Proportionality prevents the method from becoming a universal paperwork generator. The record depth and assurance burden should rise when decisions are hard to reverse, affect rights or safety, propagate widely, depend on volatile assumptions, involve uncertain evidence, or authorize automated state change. Low-consequence ephemeral choices may require only identity, outcome, and a short-lived receipt. High-consequence decisions may require independent review, preserved dissent, explicit counterfactuals, notice, redress, and long-term reconstructability.</p>
<div class="tableWrap"><table><tbody><tr><th>Envelope depth = f(consequence, reversibility, uncertainty, recurrence, propagation, sensitivity) Candidate proportionality function; no universal weights are claimed.</th></tr></tbody></table></div>
<h3>2.6 Counterfactual Boundary</h3>
<p>A rationale says why a decision was chosen. A Counterfactual Boundary asks what conditions would have caused the same legitimate decision-maker to choose differently. The distinction matters because post-hoc explanations often become unfalsifiable. A decision record that says approve because risk is acceptable provides little help when the definition of acceptable is lost. A boundary might instead record: approval depended on measured load remaining below X, the source identity being authenticated, a named control remaining active, or an affected party receiving notice before execution.</p>
<p>The boundary is provisional and consequence-scaled. It may be infeasible or misleading for creative, exploratory, or highly tacit judgment. It may invite hindsight bias or false precision. For that reason it should capture material conditions known at decision time, not every imaginable alternative. Its value must be empirically tested: does preserving the boundary improve reconstruction, trigger quality, correction speed, or inter-rater agreement beyond ordinary rationale and assumptions?</p>
<h3>2.7 Reconsideration Trigger</h3>
<p>A Reconsideration Trigger is a detectable change requiring authorized review of an earlier decision. The trigger is not the correction, reversal, appeal, redress, or remediation itself. It is the condition that reopens the question. Candidate trigger classes include a material evidence delta, invalidated assumption, changed authority or jurisdiction, policy amendment, environmental change, consequence escalation, dependency failure, time threshold, repeated anomaly, or changed system state.</p>
<div class="tableWrap"><table><tbody><tr><th>Trigger class</th><th>Example</th><th>Required response</th></tr><tr><td>Evidence</td><td>Authenticated source contradicts the original basis</td><td>Assess materiality; preserve evidence delta</td></tr><tr><td>Assumption</td><td>Expected operating range no longer holds</td><td>Review rationale and counterfactual boundary</td></tr><tr><td>Authority or jurisdiction</td><td>Delegation expires or affected domain changes</td><td>Stop state change; revalidate decision authority</td></tr><tr><td>Policy</td><td>Governing rule is amended, superseded, or suspended</td><td>Determine prospective and retrospective effect</td></tr><tr><td>Environment</td><td>Material, market, threat, staffing, or physical condition changes</td><td>Test whether original fit still exists</td></tr><tr><td>Consequence</td><td>A low-risk local action becomes a high-impact repeated action</td><td>Raise envelope and assurance tier</td></tr><tr><td>Dependency</td><td>Control, data source, vendor, model, or sensor becomes unreliable</td><td>Quarantine dependent conclusions</td></tr><tr><td>Time</td><td>Decision reaches review date or evidence becomes stale</td><td>Revalidate or expire</td></tr><tr><td>Observed state</td><td>Outcome diverges from expected completion state</td><td>Create failure receipt and reopen</td></tr></tbody></table></div>
<h3>2.8 Maintainable institutional judgment</h3>
<div class="tableWrap"><table><tbody><tr><th>PROVISIONAL DEFINITION Maintainable institutional judgment is the institutional capacity to preserve enough judgment to understand why a decision fit its original reality, detect when that fit fails, and reopen the decision through legitimate authority without pretending the institution always knew.</th></tr></tbody></table></div>
<p>The term shifts the goal from passive institutional memory to an active maintenance capability. Memory can preserve a statement. Judgment maintenance preserves the statement&#x27;s answerability to evidence, assumptions, authority, consequence, and outcome. The institution can then distinguish four states: the original decision was reasonable and remains valid; the original decision was reasonable but its conditions changed; the original decision was defective under information already available; or the record is insufficient to decide. Each state has different accountability implications.</p>
<h3>2.9 History, interpretation, and governed reinterpretation</h3>
<p>The July 31 constitutional descendant separates three objects. History is what occurred and what was preserved. Institutional interpretation is what the institution was justified in concluding from the evidence, policy, authority, jurisdiction, and uncertainty available at decision time. Governed reinterpretation is what the institution becomes justified in concluding after a material change in the evidential landscape. The correction path must preserve all three rather than replacing the first two with the newest conclusion.</p>
<p class="figureCaption"><em>Figure 2. Decision continuity, reconsideration, and explicit descendant correction.</em></p>
<p>Evidence does not self-authorize a replacement decision. A remote node, model, analyst, or reviewer may submit authenticated evidence or a correction petition. Local legitimate authority must determine materiality and effective-state change within its jurisdiction. Different legitimate institutions may preserve the same evidence and reach different interpretations under different constitutions or values. The architecture seeks convergence on evidence identity and lineage, not manufactured consensus.</p>
<h3>2.10 Correction without historical rewrite</h3>
<p><strong>1. </strong>Reference the immutable history and original interpretation.</p>
<p><strong>2. </strong>Identify the new evidence or invalidated condition as a material delta.</p>
<p><strong>3. </strong>Validate the source, custody, relevance, and uncertainty of the delta.</p>
<p><strong>4. </strong>Validate jurisdiction and correction authority.</p>
<p><strong>5. </strong>Record review, dissent, and the allowed disposition.</p>
<p><strong>6. </strong>Create an explicit descendant decision: uphold, clarify, narrow, amend, supersede, withdraw, recant, reopen, remediate, escalate, or defer unresolved.</p>
<p><strong>7. </strong>Project the new effective state only after authorization.</p>
<p><strong>8. </strong>Link notices, downstream remediation, and independent assurance when required.</p>
<p><strong>9. </strong>Preserve the correction as challengeable and supersedable by a later descendant.</p>
<div class="tableWrap"><table><tbody><tr><th>LOCKED LINE The past has not changed. The receipts have not changed. The institution&#x27;s justification may change.</th></tr></tbody></table></div>
<h2>Agentic and Technical Consequences</h2>
<h3>3.1 The agent handoff problem</h3>
<p>Modern agent systems divide work among models, tools, services, and human reviewers. The visible transcript is rarely the entire operational state. Tool calls mutate external systems; prompts omit prior constraints; summaries compress dissent; model replacement changes behavior; memory systems retrieve context probabilistically; and authorization is often attached to credentials rather than the purpose for which the credential was granted. A useful handoff therefore needs more than conversation history.</p>
<p>Recent work on event-sourced memory for heterogeneous coding agents and agent-specific extensions of W3C provenance confirms that agent continuity, traceability, and cross-tool handoff are active research problems. Those approaches overlap strongly with the transport, lineage, and reconstructability concerns of Continuity Calculus. The additional NULLWORKS claim is that provenance and memory must be bound to constitutional authority, explicit state transitions, completion definitions, correction lineage, and final human control when consequences require it.</p>
<h3>3.2 Capability is not authority</h3>
<p>An agent may possess a token that can update a database, send an email, deploy code, or purchase a service. Technical capability answers can it execute? Constitutional authority answers may it execute this action, for this purpose, on this target, during this time, under these constraints, with this consequence owner, and with what stop conditions? Treating credentials as complete authority collapses these questions. The result is overbroad delegation and ambiguous accountability.</p>
<p>The packet should therefore bind grants and prohibitions to identity, tenant or institution, target, action class, risk class, purpose, context references, expiration, revocation, completion definition, and escalation path. High-consequence ambiguity should fail closed or route to an accountable human. Human authority is not a decorative approval field; it is a constitutional boundary over legitimate state change.</p>
<h3>3.3 Completion is an observable contract</h3>
<p>Agent systems frequently confuse a successful tool response with a successful outcome. A deployment command returning 200 does not prove the intended site is live. A message being accepted by an API does not prove it reached the intended person. A file being generated does not prove it contains the requested evidence. Continuity Calculus requires explicit completion definitions that connect the action to an observable state and identify the verifier and consequence owner.</p>
<div class="tableWrap"><table><tbody><tr><th>Task</th><th>Weak completion claim</th><th>Observable completion definition</th></tr><tr><td>Publish a paper</td><td>File generated</td><td>Public artifact resolves at approved route; hash and release receipt match</td></tr><tr><td>Send a governed notice</td><td>API accepted request</td><td>Correct recipient, body, attachment, timestamp, and provider receipt verified</td></tr><tr><td>Repair equipment</td><td>Component replaced</td><td>Target failure no longer occurs under defined load; inspection and evidence preserved</td></tr><tr><td>Update policy</td><td>Text changed</td><td>Authorized descendant ratified; prior version retained; effective date and scope projected</td></tr><tr><td>Recover data</td><td>Records imported</td><td>Expected records reconcile to source counts and hashes; exceptions classified</td></tr></tbody></table></div>
<h3>3.4 Security, privacy, retention, and selective disclosure</h3>
<p>Preserving context can become surveillance if the architecture assumes that more data is always better. The framework must therefore be paired with purpose limitation, data minimization, storage limitation, access control, and deletion or redaction receipts. GDPR Article 5 provides a clear external expression of these principles: personal data should be adequate, relevant, limited to what is necessary, accurate, and retained no longer than necessary for the purpose. Continuity does not override those duties.</p>
<p>The implementation pattern is to separate the existence and integrity of evidence from universal disclosure of its content. A packet may carry a content-addressed reference, classification, retention state, and proof of prior existence while keeping sensitive material in an encrypted evidence vault. A receiver receives the minimum authorized projection. Withheld paths, redactions, and deletion actions leave bounded receipts. Some future decisions may become less reconstructable because lawful deletion is more important than institutional convenience; that loss should be explicit rather than secretly circumvented.</p>
<p>Cryptography can protect transport, custody, and tamper evidence. It cannot by itself prove intended meaning, legitimate jurisdiction, complete context, or moral and legal validity. A signed wrong interpretation is still wrong. A hash can show that a packet did not change after signing; it cannot show that the packet included the evidence or authority it should have included.</p>
<h3>3.5 V0.6 implementation evidence</h3>
<p>The current NULLWORKS reference implementation is an internal alpha, not a production deployment. Its governed record describes a fail-closed six-layer validator, deterministic packet hashing and governed diffs, append-only packet and receipt persistence, context freshness and minimum-necessary-context checks, capability grants and revocations, replay protection, authenticated federation, constitutional policy compilation, selective disclosure, encrypted transport, key-custody boundaries, certificate lifecycle, deployment gateway, recovery drills, tenant-isolation checks, field-pilot controls, challenge packets, and a human adjudication surface.</p>
<p>The implementation record preserves a false-green assurance failure: an earlier continuous-integration check did not discover the intended full suite. The gap was repaired and retained as evidence that a green status is not proof that the required tests ran. The V0.6 merge records 70 discovered tests passing on Python 3.11, 3.12, and 3.13. This is evidence of the bounded reference suite, not proof of production security, cross-organization interoperability, field benefit, or independent assurance.</p>
<div class="tableWrap"><table><tbody><tr><th>Evidence state</th><th>Current claim</th><th>Excluded inference</th></tr><tr><td>Internal canon</td><td>Six-layer method and invariants are locked NULLWORKS doctrine</td><td>Not universal or academically complete</td></tr><tr><td>Reference code</td><td>V0.1-V0.6 implementation lineage exists</td><td>Not a customer production system</td></tr><tr><td>Automated tests</td><td>70 discovered tests passed on three Python versions</td><td>Not hostile-network or field validation</td></tr><tr><td>Failure receipt</td><td>False-green discovery gap was preserved and repaired</td><td>Not proof future assurance gaps are impossible</td></tr><tr><td>External challenge package</td><td>Portable challenge machinery exists</td><td>External review has not been executed</td></tr><tr><td>Field-pilot controls</td><td>Consent and bounded telemetry controls are specified</td><td>No actual pilot outcome or ROI claim</td></tr></tbody></table></div>
<h2>Challenge, Measurement, and Formalization</h2>
<h3>4.1 Relationship to adjacent disciplines</h3>
<p class="figureCaption"><em>Figure 3. Continuity Calculus as a governed composition of adjacent disciplines.</em></p>
<div class="tableWrap"><table><tbody><tr><th>Adjacent field</th><th>What it already preserves</th><th>Remaining integration question</th></tr><tr><td>W3C PROV</td><td>Entities, activities, agents, derivations, responsibility, provenance bundles</td><td>Does not itself define local decision authority, completion, materiality, or correction legitimacy</td></tr><tr><td>Architecture Decision Records</td><td>Decision, context, status, consequences</td><td>Usually software-architecture scoped; assurance, jurisdiction, state projection, and reconsideration vary</td></tr><tr><td>Event sourcing</td><td>Append-only events and reconstructable state</td><td>Replaying events does not by itself reconstruct meaning, authority, or justified interpretation</td></tr><tr><td>Temporal databases</td><td>Valid time, transaction time, historical states</td><td>Temporal accuracy does not itself define rationale, evidence class, or decision rights</td></tr><tr><td>Records management</td><td>Reliability, authenticity, integrity, usability, retention, disposition</td><td>Often governs records broadly rather than a consequence-scaled decision handoff contract</td></tr><tr><td>Belief revision</td><td>Formal operations for expansion, contraction, and revision under new information</td><td>Typically models belief states, not institutional jurisdiction, operational effects, notice, or remediation</td></tr><tr><td>NIST AI RMF</td><td>Govern, Map, Measure, Manage; context, oversight, lifecycle risk</td><td>Framework-level risk outcomes rather than a canonical cross-agent decision packet</td></tr><tr><td>Safety and assurance cases</td><td>Structured claims, evidence, argument, hazards, review</td><td>Domain-specific implementations may not preserve everyday handoff semantics and operational lineage</td></tr><tr><td>Agent provenance / event-sourced memory</td><td>Traceable prompts, responses, actions, shared event logs, handoff projections</td><td>Emerging systems may not bind evidence to consequence-scaled human authority and governed reinterpretation</td></tr></tbody></table></div>
`;