export const paperPart04 = `<p><strong>12. </strong>Does the six-layer constitution require a descendant amendment after hostile cross-domain use?</p>
<h3>6.4 Conclusion</h3>
<p>Institutions do not fail only because they lack data. They fail because data is separated from meaning, meaning from context, context from authority, authority from state, and state from proof. The result is a record that can be transported but not legitimately used, repeated but not challenged, corrected but not historically understood, or automated without the judgment that once bounded it.</p>
<p>Continuity Calculus proposes that the useful whole should travel together, in proportion to consequence. A Continuity Packet preserves the dimensions required for a bounded handoff. A Minimum Continuity Envelope keeps that requirement practical. A Counterfactual Boundary and Reconsideration Trigger make long-lived decisions maintainable. Governed reinterpretation lets an institution learn without rewriting the past. Receipts preserve bounded evidence without claiming universal truth. Human authority remains final where ambiguity creates consequence.</p>
<p>The theory is not finished, and it should not pretend to be. Its next legitimate step is not a larger claim. It is a bounded external test: compare a real workflow with and without the envelope; measure reconstructability, state mismatch, correction quality, rework, privacy burden, and operator experience; submit the result to hostile review; preserve the failures; and create the next explicit descendant.</p>
<div class="tableWrap"><table><tbody><tr><th>FINISH-LINE DOCTRINE The student never finishes. The experiment must. Every bounded build, test, handoff, correction, and publication therefore requires an honest local completion gate and a preserved receipt.</th></tr></tbody></table></div>
<h2>Appendix A. Minimum Continuity Envelope - Reference Schema</h2>
<div class="tableWrap"><table><tbody><tr><th>Field</th><th>Purpose</th><th>Applicability</th></tr><tr><td>envelope_id</td><td>Stable identifier</td><td>Always</td></tr><tr><td>parent_id / version</td><td>Lineage and supersession</td><td>When descendant exists</td></tr><tr><td>decision_or_action</td><td>Bounded proposition or requested change</td><td>Always</td></tr><tr><td>actor_identity</td><td>Human, agent, tool, node, organization</td><td>Always</td></tr><tr><td>authority_basis</td><td>Grant, role, policy, jurisdiction, prohibitions, expiry</td><td>For interpretation or state change</td></tr><tr><td>source_evidence</td><td>References, classes, hashes, custody, access state</td><td>Consequential decisions</td></tr><tr><td>canonical_terms</td><td>Definitions, units, modality, known ambiguity</td><td>When semantic drift is possible</td></tr><tr><td>mission_and_intent</td><td>Current objective and precedence</td><td>When multiple objectives exist</td></tr><tr><td>material_assumptions</td><td>Conditions required for fit</td><td>When outcome depends on them</td></tr><tr><td>rationale_and_alternatives</td><td>Reason and rejected options</td><td>Scaled to consequence</td></tr><tr><td>before_state</td><td>Preserved state before action</td><td>Operational transition</td></tr><tr><td>requested_transition</td><td>Proposed state change</td><td>Operational transition</td></tr><tr><td>completion_definition</td><td>Observable outcome and verifier</td><td>Executable task</td></tr><tr><td>uncertainty_and_dissent</td><td>Unknowns, confidence, disagreement</td><td>When material</td></tr><tr><td>counterfactual_boundary</td><td>Conditions that would change choice</td><td>Medium/high consequence</td></tr><tr><td>reconsideration_trigger</td><td>Future evidence or state requiring review</td><td>Long-lived/state-dependent decision</td></tr><tr><td>verification_plan</td><td>Tests, reviewer class, evidence required</td><td>Consequential completion</td></tr><tr><td>receipt</td><td>Source, mutations, checks, result, after-state</td><td>After transformation</td></tr><tr><td>retention_and_disclosure</td><td>Purpose, sensitivity, retention, deletion, projection</td><td>Sensitive or regulated data</td></tr><tr><td>notice_and_redress</td><td>Affected parties, appeal, remediation</td><td>Rights or consequence affecting</td></tr></tbody></table></div>
<h2>Appendix B. Failure-Mode and Red-Team Catalog</h2>
<div class="tableWrap"><table><tbody><tr><th>Failure mode</th><th>Description</th><th>Candidate control</th></tr><tr><td>Lexical drift</td><td>Canonical term mutates or transcription error becomes doctrine</td><td>Vocabulary binding; ambiguity preservation; correction receipt</td></tr><tr><td>Modality drift</td><td>Artifact form is substituted for requested outcome</td><td>Deliverable contract and observable completion</td></tr><tr><td>Completion drift</td><td>Two workers use incompatible definitions of done</td><td>One authoritative completion contract</td></tr><tr><td>Context drift</td><td>Stale, irrelevant, or unauthorized history steers work</td><td>Freshness, relevance, minimization, source labels</td></tr><tr><td>Authority drift</td><td>Capable actor exceeds grant or jurisdiction</td><td>Bound grants, prohibitions, expiry, consequence owner</td></tr><tr><td>Assurance drift</td><td>Execution evidence represented as outcome proof</td><td>Evidence classes and independent verification gate</td></tr><tr><td>History overwrite</td><td>Correction replaces original event or interpretation</td><td>Append-only parent-descendant lineage</td></tr><tr><td>False materiality</td><td>Convenience or model output presented as new evidence</td><td>Evidence delta and materiality test</td></tr><tr><td>Remote coercion</td><td>Federated sender forces local interpretation or state change</td><td>Local jurisdiction and decision authority</td></tr><tr><td>False consensus</td><td>Divergent legitimate interpretations are collapsed</td><td>Explicit divergence receipt</td></tr><tr><td>Privacy overcollection</td><td>Continuity becomes unlimited memory or surveillance</td><td>Minimum projection, retention, deletion receipt</td></tr><tr><td>Proof-scope inflation</td><td>Receipt or signature claimed to prove truth or legitimacy</td><td>Bounded assurance statement</td></tr><tr><td>False-green testing</td><td>Status passes while intended tests never ran</td><td>Test-discovery verification and preserved failure receipt</td></tr><tr><td>Trigger flooding</td><td>Review system overwhelmed by low-materiality changes</td><td>Consequence tier, threshold calibration, sampling</td></tr><tr><td>Trigger suppression</td><td>No path exists to reopen a stable but defective decision</td><td>Redress and challenge access</td></tr><tr><td>Correction chain break</td><td>Descendant cannot be traced to parent evidence and authority</td><td>Lineage hash, changed-field ledger, effective-state projection</td></tr></tbody></table></div>
<h2>Appendix C. Candidate Formal Model</h2>
<p>The following notation is an operational research scaffold. It does not establish mathematical completeness, independence of dimensions, calibrated measurement, or a universal calculus.</p>
<div class="tableWrap"><table><tbody><tr><th>CP_t = &lt;D_t, M_t, C_t, A_t, S_t, V_t&gt;</th></tr></tbody></table></div>
<div class="tableWrap"><table><tbody><tr><th>T_k(CP_t) -&gt; CP_(t+1), subject to I_D, I_M, I_C, I_A, I_S, I_V</th></tr></tbody></table></div>
<p>Each I_i is an invariant set for the corresponding constitutional dimension. A transformation can be accepted only if mandatory invariants pass or the packet fails closed with a receipt. Domain policy determines which invariants are mandatory and which may remain unresolved.</p>
<div class="tableWrap"><table><tbody><tr><th>q_t in [0,1]^6; l_t = 1 - q_t</th></tr></tbody></table></div>
<p>q_t is an assessment vector, not an objective physical quantity. Scores may be ordinal, categorical, or probabilistic. Veto conditions should not be averaged away.</p>
<div class="tableWrap"><table><tbody><tr><th>R_t = {DeltaE, DeltaX, DeltaA, DeltaJ, DeltaP, DeltaEnv, DeltaK, DeltaS, DeltaTime}</th></tr></tbody></table></div>
<p>R_t is the set of candidate reconsideration triggers: changes in evidence, assumptions, authority, jurisdiction, policy, environment, consequence, system state, or time. A trigger opens review; it does not itself authorize state change.</p>
<div class="tableWrap"><table><tbody><tr><th>GR(parent, DeltaE, materiality, authority, review) -&gt; descendant + effective_state_receipt</th></tr></tbody></table></div>
<p>GR is governed reinterpretation. It requires an immutable parent, inspectable evidence delta, materiality assessment, valid authority and jurisdiction, review record, allowed disposition, and effective-state receipt.</p>
<div class="tableWrap"><table><tbody><tr><th>DR = mean(r_E, r_R, r_X, r_A, r_S, r_V, r_T)</th></tr></tbody></table></div>
<div class="tableWrap"><table><tbody><tr><th>RE = sum_j p_j * C_j</th></tr></tbody></table></div>
<p>Decision Reconstructability and Rework Exposure are candidate measurements. The first assesses recoverability of the decision problem; the second estimates future burden from identified continuity defects. Both require domain-specific validation and uncertainty reporting.</p>
<h2>Appendix D. Implementation Pattern Catalog</h2>
<div class="tableWrap"><table><tbody><tr><th>Pattern</th><th>Purpose</th></tr><tr><td>Structured decision envelope</td><td>Typed record carrying the minimum consequence-scaled continuity dimensions.</td></tr><tr><td>Content-addressed evidence reference</td><td>Stable link between claim and preserved evidence without universal disclosure.</td></tr><tr><td>Minimum-necessary context projection</td><td>Receiver-specific view containing only relevant and authorized context.</td></tr><tr><td>Tiered retention</td><td>Retention period and assurance depth tied to purpose, consequence, law, and sensitivity.</td></tr><tr><td>Encrypted evidence vault</td><td>Separated custody for sensitive source material with reference and access receipts.</td></tr><tr><td>Selective disclosure receipt</td><td>Declared allowed, required, forbidden, disclosed, and withheld paths.</td></tr><tr><td>Redacted descendant</td><td>Public or lower-clearance artifact linked to a protected parent without pretending equivalence.</td></tr><tr><td>Immutable event receipt</td><td>Append-only source, action, mutation, authority, and outcome record.</td></tr><tr><td>Deletion receipt</td><td>Proof that a governed deletion or redaction action occurred within bounded scope.</td></tr><tr><td>Proof of prior existence</td><td>Commitment that material existed at a time without necessarily retaining or revealing it indefinitely.</td></tr><tr><td>Parent-descendant lineage</td><td>Explicit inheritance, changed fields, unchanged fields, authority, and effective state.</td></tr><tr><td>Challenge ledger</td><td>Criticism, evidence, permission, conflict, disposition, and correction link.</td></tr><tr><td>Materiality gate</td><td>Prevents weak context, convenience, or model output from silently changing effective interpretation.</td></tr><tr><td>Authority and jurisdiction validation</td><td>Separates transport of evidence from legitimate local decision power.</td></tr><tr><td>Effective-state projection</td><td>Current operational view derived from authorized descendants while history remains append-only.</td></tr><tr><td>Interpretive divergence receipt</td><td>Preserves different legitimate conclusions without false consensus.</td></tr><tr><td>Review-trigger monitor</td><td>Detects evidence, state, authority, policy, time, and dependency changes.</td></tr><tr><td>Decision reconstruction test</td><td>Blind or semi-blind test of whether future reviewers can recover the decision problem.</td></tr></tbody></table></div>
<h2>Appendix E. Release Audit</h2>
<div class="tableWrap"><table><tbody><tr><th>Claim class</th><th>Status in this release</th><th>Publication rule</th></tr><tr><td>Locked NULLWORKS doctrine</td><td>Canonical definition, six layers, packet, receipts, human authority, append-only correction</td><td>May be stated as NULLWORKS doctrine, not universal fact</td></tr><tr><td>Source-supported interpretation</td><td>V0.6 implementation state, test lineage, bounded assurance conclusions</td><td>Must remain within source scope</td></tr><tr><td>Provisional definition</td><td>Rework Tax, Minimum Continuity Envelope, Counterfactual Boundary, Reconsideration Trigger, Decision Reconstructability</td><td>Must remain visibly provisional</td></tr><tr><td>Hypothesis</td><td>Bureaucracy as normalized rework; agent acceleration of inherited assumptions; value of counterfactual capture</td><td>Requires contrary evidence and falsification conditions</td></tr><tr><td>Open research question</td><td>Formal completeness, layer sufficiency, measurement calibration, external value</td><td>No resolved claim</td></tr><tr><td>Rejected claim</td><td>Mathematical completeness, production readiness, independent assurance, regulatory compliance</td><td>Prohibited</td></tr><tr><td>Blocked claim</td><td>Academic novelty and exact delta from unseen predecessor paper</td><td>Prohibited until evidence exists</td></tr></tbody></table></div>
<h2>References</h2>
<p><strong>[1] NULLWORKS. </strong>Continuity Calculus Canon v0.1. Governed internal record, July 29, 2026. Git commit lineage includes 47675312059e387c69dcbe188f79dad6f5e49dc0; locked record blob SHA 3250823905f29cfd20254a146363a443f828025a.</p>
<p><strong>[2] NULLWORKS. </strong>Continuity Calculus V0.6 current pointer and deployment-readiness truth boundary. Governed internal record, July 29, 2026; merge commit 7e89828f221eba85f648e82aa77468da4230a704.</p>
<p><strong>[3] NULLWORKS. </strong>Governed Reinterpretation and Inspectable Correction - Constitutional Amendment V0.7. Governed internal descendant, July 31, 2026; blob SHA 93df95522b981ffa5d58c8a67c567d3348637b47.</p>
<p><strong>[4] Moreau, L., Missier, P., et al. </strong>PROV-DM: The PROV Data Model. W3C Recommendation, 2013.</p>
<p><strong>[5] Tabassi, E. </strong>Artificial Intelligence Risk Management Framework (AI RMF 1.0). NIST AI 100-1, National Institute of Standards and Technology, 2023. doi:10.6028/NIST.AI.100-1.</p>
<p><strong>[6] National Institute of Standards and Technology. </strong>NIST SP 800-171 Rev. 3 and SP 800-171A Rev. 3: audit record content and assessment evidence, 2024.</p>
<p><strong>[7] National Archives and Records Administration. </strong>NARA Bulletin 2025-01: Metadata Guidance for the Transfer of Classified Electronic Records, January 22, 2025.</p>
<p><strong>[8] National Archives and Records Administration. </strong>Guidance on Managing Web Records: trustworthy records, content, context, structure, reliability, authenticity, integrity, and usability.</p>
<p><strong>[9] European Union. </strong>Regulation (EU) 2016/679 (General Data Protection Regulation), Article 5: purpose limitation, data minimisation, accuracy, storage limitation, integrity, and confidentiality.</p>
<p><strong>[10] Microsoft. </strong>Event Sourcing Pattern. Azure Architecture Center, current documentation accessed August 1, 2026.</p>
<p><strong>[11] Nygard, M.; Architecture Decision Record community. </strong>Architecture Decision Records: documenting important decisions with context and consequences.</p>
<p><strong>[12] Alchourrón, C. E., Gärdenfors, P., and Makinson, D. </strong>On the Logic of Theory Change: Partial Meet Contraction and Revision Functions. Journal of Symbolic Logic 50(2), 1985, pp. 510-530.</p>
<p><strong>[13] Vaughan, D. </strong>The Challenger Launch Decision: Risky Technology, Culture, and Deviance at NASA. University of Chicago Press, 1996; enlarged edition 2016.</p>
<p><strong>[14] U.S. Government Accountability Office. </strong>Reports and testimony on knowledge transfer, phased retirement, workforce succession, and institutional knowledge, including GAO-17-536 and GAO-19-696T.</p>
<p><strong>[15] Souza, R., et al. </strong>PROV-AGENT: Unified Provenance for Tracking AI Agent Interactions in Agentic Workflows. arXiv:2508.02866, 2025.</p>
<p><strong>[16] dos Santos Filho, E. B. </strong>ESAA-Conversational: An Event-Sourced Memory Layer for Continuity, Handoff, and Curation Across Heterogeneous LLM Coding Agents. arXiv:2606.23752, 2026.</p>
<p><strong>[17] Operational Recovery Series, NULLWORKS. </strong>The Workflow on Paper Was Never the Workflow v0.6; From Runtime Truth to Operational Recovery v0.4; TAC OPS: A Governed Label Recovery Architecture v0.4. Final red-team boundary packet, July 27, 2026.</p>
<h3>Source Links</h3>
<p class="bullet">W3C PROV-DM</p>
<p class="bullet">NIST AI RMF 1.0</p>
<p class="bullet">NIST AI RMF Core</p>
<p class="bullet">NARA Bulletin 2025-01</p>
<p class="bullet">NARA trustworthy web records guidance</p>
<p class="bullet">GDPR Article 5</p>
<p class="bullet">Azure Event Sourcing Pattern</p>
<p class="bullet">Architecture Decision Record examples</p>
<p class="bullet">PROV-AGENT</p>
<p class="bullet">ESAA-Conversational</p>
<h2>Release Receipt</h2>
<div class="tableWrap"><table><tbody><tr><th>Field</th><th>Value</th></tr><tr><td>Document</td><td>Continuity Calculus: Preserving Institutional Judgment Across Time, Systems, and Agents</td></tr><tr><td>Version</td><td>Public Research Release 2.0</td></tr><tr><td>Author / Human Authority</td><td>Mason Perry</td></tr><tr><td>Organization</td><td>NULLWORKS</td></tr><tr><td>Release date</td><td>August 1, 2026</td></tr><tr><td>Parent doctrine</td><td>Continuity Calculus Canon v0.1, July 29, 2026</td></tr><tr><td>Parent implementation</td><td>V0.6 deployment-readiness merge and lock, July 29, 2026</td></tr><tr><td>Constitutional descendant</td><td>Governed Reinterpretation V0.7, July 31, 2026</td></tr><tr><td>External prior-art review</td><td>Primary-source map completed for publication; not an academic systematic review</td></tr><tr><td>Internal red-team</td><td>Major objections and falsification conditions included in Section 6 and Appendix B</td></tr><tr><td>Independent external assurance</td><td>NOT PERFORMED</td></tr><tr><td>Production deployment</td><td>NOT PERFORMED</td></tr><tr><td>Field pilot</td><td>NOT EXECUTED</td></tr><tr><td>Exact predecessor manuscript delta</td><td>BLOCKED - predecessor artifact unavailable</td></tr><tr><td>Truth boundary</td><td>Public theoretical and exploratory release; no certification, compliance, universal-validity, or mathematical-completeness claim</td></tr></tbody></table></div>
<p><strong>NO RECEIPT, NO SYNC. NO FAKE FINISH LINES. HUMAN AUTHORITY REMAINS FINAL.</strong></p>
`;