export const paperPart03 = `<p>The framework should therefore avoid the claim that no one has preserved context, provenance, rationale, authority, or correction before. Its defensible research contribution is an explicit constitutional integration: a decision handoff object that treats meaning, minimum context, jurisdiction, operational state, verification, and future reconsideration as jointly required dimensions whose depth is scaled by consequence.</p>
<h3>4.2 Candidate Continuity Loss Vector</h3>
<div class="tableWrap"><table><tbody><tr><th>q_t = [q_D, q_M, q_C, q_A, q_S, q_V], where each q_i is an assessed adequacy score in [0,1] Operational scoring candidate, not a validated interval measurement.</th></tr></tbody></table></div>
<div class="tableWrap"><table><tbody><tr><th>l_t = 1 - q_t Continuity loss vector: degradation by constitutional dimension.</th></tr></tbody></table></div>
<p>The vector makes one practical point: a handoff can be strong in one dimension and dangerously weak in another. A cryptographically protected packet may have q_D near one while q_C or q_A is low. A detailed narrative may preserve context but fail state or verification. Collapsing the vector into a single score can hide veto conditions, so any aggregate should retain fail-closed rules for authority, prohibited state transitions, source integrity, and required assurance.</p>
<div class="tableWrap"><table><tbody><tr><th>L_t = w . l_t + lambda*I_unauthorized + mu*I_state_mismatch + nu*I_assurance_gap Candidate risk-weighted loss with explicit veto indicators. Weights require domain calibration.</th></tr></tbody></table></div>
<h3>4.3 Decision Reconstructability</h3>
<p>Decision Reconstructability is the degree to which an authorized future observer can recover the evidence, rationale, assumptions, authority, state transition, and conditions for review. A useful test is not whether the observer agrees with the decision, but whether the observer can reproduce the decision problem as it was understood at the time, identify where uncertainty or discretion entered, and distinguish later knowledge from original knowledge.</p>
<div class="tableWrap"><table><tbody><tr><th>DR = (r_E + r_R + r_X + r_A + r_S + r_V + r_T) / 7 Candidate component scores: evidence, rationale, assumptions, authority, state, verification, and triggers.</th></tr></tbody></table></div>
<p>A reconstructability test can be performed by a blinded authorized reviewer who receives the preserved envelope but not the original conclusion. The reviewer attempts to identify the option set, material evidence, authority, likely action, and review conditions. Agreement, time-to-reconstruction, missing-field count, and confidence calibration provide telemetry. A high DR score does not prove the decision was good; it shows that the decision remains inspectable.</p>
<h3>4.4 Rework Exposure</h3>
<div class="tableWrap"><table><tbody><tr><th>RE = sum_j p_j * (C_reconstruct,j + C_reverse,j + C_escalate,j + C_verify,j + C_cascade,j) Expected future burden across identified continuity-failure modes j.</th></tr></tbody></table></div>
<p>Rework Exposure is prospective, not a claim of certain savings. The formula is useful only if recurrence probabilities and costs can be estimated without treating every future activity as avoidable. It should include uncertainty ranges, avoid double counting, and compare the repair cost of better continuity against the expected loss. Some defects should be monitored rather than repaired because the envelope cost exceeds likely lifetime rework. Others should be fixed immediately because they create catastrophic or cascading risk.</p>
<h3>4.5 Telemetry that does not reward theater</h3>
<div class="tableWrap"><table><tbody><tr><th>Metric</th><th>What it may reveal</th><th>Anti-gaming caution</th></tr><tr><td>Packet validity rate</td><td>Required dimensions present and internally consistent</td><td>Can reward over-documentation unless proportionality is audited</td></tr><tr><td>Decision reconstruction time</td><td>Time for authorized observer to recover decision basis</td><td>Fast reconstruction can still reproduce a bad decision</td></tr><tr><td>Missing material field rate</td><td>Fields later needed but absent at decision time</td><td>Hindsight can inflate what seems material</td></tr><tr><td>Authority exception rate</td><td>Actions attempted outside grant or jurisdiction</td><td>More detected exceptions may mean better controls, not worse behavior</td></tr><tr><td>State mismatch rate</td><td>Claimed completion differs from observed after-state</td><td>Measurement quality controls the result</td></tr><tr><td>Reconsideration trigger precision</td><td>Triggers that produce material review versus noise</td><td>Low trigger rate can mean missed problems</td></tr><tr><td>Correction latency</td><td>Time from material evidence to authorized effective change</td><td>Fast correction can bypass due process</td></tr><tr><td>Original-history retrievability</td><td>Parent evidence and interpretation survive descendants</td><td>Retention law may legitimately limit retrieval</td></tr><tr><td>Divergence visibility</td><td>Authorized differing interpretations remain explicit</td><td>Consensus is not automatically the goal</td></tr><tr><td>Rework recurrence</td><td>Same continuity defect reappears after intervention</td><td>Requires stable defect classification</td></tr><tr><td>Human override quality</td><td>Overrides are reasoned, receipted, and outcome-tested</td><td>Override count alone is meaningless</td></tr></tbody></table></div>
<p>Correction count is especially ambiguous. A system with more corrections may be learning well, discovering more defects, or producing more errors. A system with few corrections may be stable, opaque, suppressing challenges, or unable to reopen decisions. Measurement must compare correction quality, consequence, baseline error, review access, and state outcomes rather than treating one count as governance success.</p>
<h3>4.6 Falsification and challenge conditions</h3>
<p>The paper should be weakened, revised, or rejected where evidence shows that its extra structure does not improve decision reconstruction, challenge quality, correction legitimacy, or operational outcomes relative to simpler alternatives. Specific falsification conditions include:</p>
<p class="bullet">A consequential class of decisions remains reliably reconstructable and corrigible from data integrity and ordinary audit logs alone.</p>
<p class="bullet">The Counterfactual Boundary adds no value beyond rationale and assumptions, or systematically invites post-hoc rationalization.</p>
<p class="bullet">The Minimum Continuity Envelope creates more burden and privacy risk than the rework or consequence it prevents.</p>
<p class="bullet">The six dimensions cannot coherently classify observed continuity failures without distortion or duplication.</p>
<p class="bullet">Independent reviewers cannot apply the layer definitions consistently enough for operational use.</p>
<p class="bullet">The correction lineage preserves history but makes present effective state ambiguous or unsafe.</p>
<p class="bullet">Human authority gates become ceremonial bottlenecks rather than accountable consequence ownership.</p>
<p class="bullet">Agent systems with simpler provenance and authorization controls perform as well under adversarial and field tests.</p>
<h2>Application and Implementation</h2>
<h3>5.1 Use cases</h3>
<div class="tableWrap"><table><tbody><tr><th>Domain</th><th>Continuity envelope emphasis</th><th>Expected value</th></tr><tr><td>Maintenance and operations</td><td>Repair decisions, hidden workarounds, before/after state, load tests, recurring failures</td><td>Prevents component replacement from erasing causal context</td></tr><tr><td>AI-agent workflows</td><td>Task intent, canonical terms, grants, tool effects, review state, model/version, receipts</td><td>Reduces drift across agents and model replacement</td></tr><tr><td>Policy and compliance</td><td>Authority, jurisdiction, policy version, evidence, effective date, appeal and correction path</td><td>Separates the historical decision from current governing state</td></tr><tr><td>Healthcare or safety decisions</td><td>Evidence, uncertainty, consequence owner, thresholds, dissent, review trigger</td><td>Supports reconstructability and redress; requires domain regulation</td></tr><tr><td>Legal and investigative records</td><td>Source chain, claims, interpretations, authority, correction lineage</td><td>Prevents later summaries from replacing original evidence</td></tr><tr><td>Software architecture</td><td>ADR context plus operational state, assurance, expiry, and reconsideration</td><td>Makes long-lived decisions reviewable when assumptions change</td></tr><tr><td>Supply chain and vendor management</td><td>Source identity, custody, delegated authority, dependency state, notice obligations</td><td>Makes remote evidence portable without transferring local jurisdiction</td></tr><tr><td>Organizational succession</td><td>Tacit rationale, decision boundaries, recurring anomalies, unresolved questions</td><td>Converts some veteran knowledge into challengeable records</td></tr></tbody></table></div>
<h3>5.2 Implementation path</h3>
<p><strong>1. </strong>Select one bounded workflow with recurring handoffs, meaningful consequence, and observable outcomes.</p>
<p><strong>2. </strong>Inventory current decisions, artifacts, authority paths, state transitions, failure modes, retention duties, and hidden workarounds.</p>
<p><strong>3. </strong>Define canonical terms and one authoritative completion contract.</p>
<p><strong>4. </strong>Design a consequence-scaled Minimum Continuity Envelope; explicitly exclude unnecessary context.</p>
<p><strong>5. </strong>Bind actor identity, authority, jurisdiction, prohibitions, expiry, stop conditions, and consequence ownership.</p>
<p><strong>6. </strong>Preserve source references, evidence classes, before-state, after-state, and append-only receipts.</p>
<p><strong>7. </strong>Define reconsideration triggers and permitted descendant dispositions.</p>
<p><strong>8. </strong>Run adversarial fixtures: stale context, lexical drift, unauthorized action, replay, false completion, missing evidence, remote coercion, history overwrite, and false assurance.</p>
<p><strong>9. </strong>Measure reconstruction time, missing material fields, state mismatch, correction latency, rework recurrence, and privacy burden against a baseline.</p>
<p><strong>10. </strong>Escalate the architecture only where the evidence supports additional cost; preserve failures and rejected hypotheses.</p>
<h3>5.3 Reference implementation patterns</h3>
<p class="bullet">Structured decision envelope with typed evidence, authority, state, and verification fields.</p>
<p class="bullet">Content-addressed evidence references and immutable event receipts.</p>
<p class="bullet">Minimum-necessary context projection and selective disclosure.</p>
<p class="bullet">Tiered retention, encrypted evidence vaults, deletion receipts, and proof of prior existence.</p>
<p class="bullet">Parent-descendant lineage with explicit changed and unchanged fields.</p>
<p class="bullet">Challenge ledger with attribution, quotation permission, conflict, and disposition.</p>
<p class="bullet">Materiality gate and jurisdiction validation before effective-state change.</p>
<p class="bullet">Effective-state projection separated from the append-only historical log.</p>
<p class="bullet">Review-trigger monitor and decision-reconstruction tests.</p>
<p class="bullet">Independent challenge packets that exclude private material and preserve truth boundaries.</p>
<h3>5.4 Publication as an implementation test</h3>
<p>This paper itself should obey the architecture it proposes. Its parent records are named. Its claims are classified. Unsupported novelty and mathematical completeness are prohibited. The V0.6 implementation evidence is separated from external assurance. Provisional concepts are visibly provisional. The missing predecessor manuscript remains unresolved rather than reconstructed. Challenges should produce public or private receipts according to permission, and accepted changes should appear as explicit descendants rather than silent edits.</p>
<h2>Red-Team Findings, Limits, and Open Questions</h2>
<h3>6.1 Internal red-team findings</h3>
<div class="tableWrap"><table><tbody><tr><th>Challenge</th><th>Severity</th><th>Disposition / required test</th></tr><tr><td>The framework may be an overgrown ADR</td><td>Medium</td><td>Test whether authority, state, verification, and reconsideration fields add measurable value beyond established decision records</td></tr><tr><td>Six layers may overlap or be incomplete</td><td>Medium</td><td>Use hostile classification exercises; allow explicit descendant amendment, not silent renaming</td></tr><tr><td>Counterfactuals may be fabricated after the fact</td><td>High</td><td>Capture at decision time where consequence warrants; label later reconstruction separately</td></tr><tr><td>Minimum envelope may become maximum bureaucracy</td><td>High</td><td>Consequence tiers, field budgets, retention limits, and burden telemetry</td></tr><tr><td>Human authority may become a ceremonial bottleneck</td><td>High</td><td>Bind authority to consequence ownership and response obligations; measure latency and override quality</td></tr><tr><td>Append-only history may conflict with deletion duties</td><td>High</td><td>Separate integrity commitments from retained content; use redaction/deletion receipts and lawful retention policy</td></tr><tr><td>Receipts may create false confidence</td><td>High</td><td>State exact proof scope; separate self-audit, test evidence, external review, and certification</td></tr><tr><td>Rework Tax may pathologize iteration</td><td>Medium</td><td>Use counterfactual cost baselines and classify productive learning separately</td></tr><tr><td>Bureaucracy hypothesis may become ideological</td><td>High</td><td>Keep low-confidence, avoid named-employer generalization, actively seek counterexamples</td></tr><tr><td>Agent risk claim may be automation exceptionalism</td><td>Medium</td><td>Compare matched human and agent workflows under equal task volume and consequence</td></tr><tr><td>Novelty claim may fail prior-art review</td><td>High</td><td>Do not claim academic novelty; publish overlap map and invite domain specialists</td></tr><tr><td>Formal scores may imply fake precision</td><td>High</td><td>Use vectors and veto conditions; calibrate per domain; publish uncertainty and scoring disagreement</td></tr></tbody></table></div>
<h3>6.2 Limitations</h3>
<p class="bullet">The framework originates in NULLWORKS operational doctrine and one internal-alpha implementation lineage; it lacks independent field replication.</p>
<p class="bullet">The six-layer model is a useful current constitution, not a demonstrated universal decomposition of institutional judgment.</p>
<p class="bullet">The proposed measurements have not been calibrated across domains or shown to predict outcomes.</p>
<p class="bullet">The paper does not resolve conflicts among transparency, privacy, deletion, intellectual property, privilege, and security.</p>
<p class="bullet">Human authority can be unjust, incompetent, unavailable, or structurally conflicted; preserving authority does not prove legitimacy.</p>
<p class="bullet">A reconstructable decision can still be wrong, discriminatory, unsafe, or unlawful.</p>
<p class="bullet">Some tacit, embodied, creative, or relational judgment may resist formal envelopes without destructive simplification.</p>
<p class="bullet">The architecture may be too expensive for low-consequence work and too weak for regulated high-consequence domains without additional controls.</p>
<p class="bullet">The exact August 1 predecessor manuscript remains unavailable, so the release cannot claim a complete paper-to-paper delta.</p>
<h3>6.3 Open research questions</h3>
<p><strong>1. </strong>Can independent reviewers apply the six dimensions with acceptable agreement?</p>
<p><strong>2. </strong>What is the smallest envelope that materially improves reconstruction for each consequence tier?</p>
<p><strong>3. </strong>Does a captured Counterfactual Boundary improve trigger precision and correction quality?</p>
<p><strong>4. </strong>How should lawful deletion affect proofs of prior existence and future reconstructability?</p>
<p><strong>5. </strong>When should local interpretive divergence be preserved, escalated, or resolved?</p>
<p><strong>6. </strong>How can authority quality and conflict be assessed without allowing the system to manufacture legitimacy?</p>
<p><strong>7. </strong>What baseline distinguishes productive iteration from avoidable rework?</p>
<p><strong>8. </strong>Which continuity failures are leading indicators of downstream incidents?</p>
<p><strong>9. </strong>Can agentic provenance standards be extended with portable authority, completion, and correction semantics?</p>
<p><strong>10. </strong>How should non-deterministic model behavior be represented in decision reconstruction and cross-version comparison?</p>
<p><strong>11. </strong>What external assurance protocol is appropriate for a method that combines technical and institutional claims?</p>
`;