export const paperPart01 = `<h2>Publication and Lineage Notice</h2>
<p>This paper is an explicit descendant of the locked NULLWORKS Continuity Calculus canon dated July 29, 2026; the V0.6 deployment-readiness implementation lock; and the July 31, 2026 governed-reinterpretation constitutional amendment. It inherits the six-layer constitutional stack and the Continuity Packet notation CP = &lt;D, M, C, A, S, V&gt;. It adds a public prior-art map, consequence-scaled decision records, maintainable institutional judgment, counterfactual boundaries, reconsideration triggers, candidate measurements, and an implementation path.</p>
<p>A separate August 1 predecessor manuscript referenced in planning records was not available to this build. Therefore this release does not claim a sentence-level or claim-by-claim delta against that unseen artifact, does not silently replace it, and does not infer its title, hash, or publication status. Its lineage claim is bounded to the governed canon and implementation records that were actually recovered.</p>
<p>The parent records remain immutable. Corrections to this release must be made as explicit descendants that preserve the source text, challenge, decision authority, changed fields, unchanged fields, resulting version, and effective publication state.</p>
<h2>Abstract</h2>
<p>Organizations routinely preserve the output of a decision while losing the conditions that made the decision intelligible: the meaning of key terms, the evidence then available, the assumptions that bounded the choice, the authority under which it was made, the state it changed, the definition of completion, and the conditions that should reopen it. This loss is costly in ordinary human workflows and more dangerous in agentic systems, where inherited assumptions can become executable at machine speed. Continuity Calculus is a NULLWORKS method for carrying data, meaning, context, authority, operational state, and verification together across transformations and handoffs. It treats continuity as a constitutional property rather than a storage feature.</p>
<p>The paper formalizes a six-dimensional Continuity Packet, distinguishes history from institutional interpretation and governed reinterpretation, proposes a Minimum Continuity Envelope for consequence-scaled decisions, and introduces the provisional concepts of Counterfactual Boundary, Reconsideration Trigger, Decision Reconstructability, Continuity Loss Vector, and Rework Exposure. It compares the framework with provenance standards, decision records, event sourcing, temporal data, records management, belief revision, privacy principles, and AI risk management. The proposed contribution is not that those disciplines are absent; it is that their partially overlapping concerns can be composed into one bounded handoff and correction contract with explicit human authority, jurisdiction, state transition, and assurance.</p>
<p>The framework remains exploratory. It does not prove universal completeness, semantic correctness, positive return on investment, or regulatory compliance. The V0.6 internal-alpha implementation passed 70 discovered tests on Python 3.11, 3.12, and 3.13 after a false-green test-discovery gap was preserved and repaired. External assurance, production deployment, and field validation remain open gates.</p>
<h2>Executive Summary</h2>
<p>Most institutions can retrieve a result. Fewer can reconstruct the judgment that produced it. A maintenance instruction remains after the machine, material, staffing, policy, or hazard that justified it has changed. A model inherits a classification label but not the dispute that defined it. A workflow preserves a completed status but not the observable condition that made completion legitimate. Each transfer can be technically correct while the useful whole decays.</p>
<p>Continuity Calculus addresses that decay by treating a handoff as a governed object rather than a payload. The canonical Continuity Packet contains six required dimensions: data and transport; meaning and semantics; context and intent; authority and constraints; operational state and transition; and verification and receipt. A transformation is valid only when the required dimensions survive, every material mutation is declared, the receiver is authorized, the state transition is legitimate, and the result is inspectable.</p>
<p class="bullet">Preserve the source, but do not confuse source integrity with meaning, legitimacy, or completion.</p>
<p class="bullet">Carry the minimum sufficient context, not the maximum possible context.</p>
<p class="bullet">Separate capability from authority and evidence from self-executing permission.</p>
<p class="bullet">Define completion as an observable state, not a worker&#x27;s assertion.</p>
<p class="bullet">Preserve history and original interpretation when later evidence justifies correction.</p>
<p class="bullet">Scale record depth, retention, review, and independent assurance to consequence.</p>
<p class="bullet">Keep consequential ambiguity under accountable human authority.</p>
<p>The core descendant idea is maintainable institutional judgment: an institution should be able to explain why a decision fit its original reality, detect when that fit fails, and reopen the decision through legitimate authority without pretending it always knew the corrected answer. This turns correction from an overwrite into an inspectable state transition.</p>
<p>The paper proposes a practical Minimum Continuity Envelope containing decision identity, actor, authority, evidence, material assumptions, rationale, before-state, intended after-state, completion definition, uncertainty, source references, verification, retention class, and a review trigger where consequence warrants it. It also proposes a Counterfactual Boundary: the conditions under which the same legitimate decision-maker would reasonably have chosen differently. Together, the envelope and boundary make future reconsideration possible without requiring an unlimited archive of everything.</p>
<p>The resulting architecture is neither a universal ontology nor a replacement for established disciplines. W3C PROV describes entities, activities, agents, derivations, and responsibility. Architecture Decision Records preserve context and consequences. Event sourcing preserves append-only change history and reconstructable state. Records management addresses trustworthy, usable records and retention. Belief revision studies rational change under new information. NIST AI RMF supplies lifecycle governance, context mapping, measurement, management, and human oversight. Continuity Calculus composes these concerns around a bounded operational question: what must travel with a consequential decision so that another authorized human or system can use, challenge, verify, and, when justified, correct it?</p>
<h2>Contents</h2>
<p><strong>1. </strong>The Operational Problem</p>
<p><strong>2. </strong>The Constitutional Architecture</p>
<p><strong>3. </strong>Agentic and Technical Consequences</p>
<p><strong>4. </strong>Challenge, Measurement, and Formalization</p>
<p><strong>5. </strong>Application and Implementation</p>
<p><strong>6. </strong>Red-Team Findings, Limits, and Open Questions</p>
<p><strong>Appendix A. </strong>Minimum Continuity Envelope</p>
<p><strong>Appendix B. </strong>Failure-Mode and Red-Team Catalog</p>
<p><strong>Appendix C. </strong>Candidate Formal Model</p>
<p><strong>Appendix D. </strong>Implementation Pattern Catalog</p>
<p><strong>Appendix E. </strong>Release Audit and References</p>
<h2>The Operational Problem</h2>
<h3>1.1 The output survives; the judgment disappears</h3>
<p>Institutional memory is often mistaken for document storage. A document may survive while the usable judgment around it disappears. The record can show what was done without showing why it was reasonable, which evidence was unavailable, whose authority controlled, which alternative was rejected, what state was expected to change, or what future observation should force review. This is not merely a documentation inconvenience. It changes the institution&#x27;s ability to distinguish a valid inherited control from a ritual, a correction from a cover-up, and a legitimate constraint from an expired assumption.</p>
<p>The loss occurs at seams: between shifts, departments, vendors, software systems, models, agents, generations of workers, policy versions, and institutions. Each participant may receive enough information to continue locally while the global reason gradually decays. By the time a failure becomes visible, the reconstruction burden is distributed across meetings, tickets, escalations, audits, duplicate analysis, emergency work, and blame. The organization may see each activity as necessary work even when the activities are recurring symptoms of the same continuity defect.</p>
<h3>1.2 Physical maintenance as the originating lens</h3>
<p>The theory emerged from a physical maintenance intuition: when a machine repeatedly fails, replacing the failed component is not enough if the system continues to recreate the condition that damaged it. A broken wire, tripped overload, clogged drain, rejected label, or unstable sensor may be the visible failure. The causal architecture includes the environment, previous repairs, material behavior, hidden workarounds, operating tempo, authority boundaries, and the reason an earlier technician chose a particular intervention. Maintenance practice therefore trains attention on state, sequence, evidence, consequence, and the difference between restoring operation and removing the leak.</p>
<p>The same distinction applies to administrative and digital work. A workflow can be made to pass today while preserving the mechanism that will generate tomorrow&#x27;s exception. A report can satisfy a template while obscuring the source uncertainty. An AI agent can complete a task exactly as instructed while the instruction is based on a stale assumption. Operational recovery requires more than a correct local action; it requires enough continuity to understand the system that made the action necessary.</p>
<h3>1.3 The Rework Tax</h3>
<p>Rework Tax is a provisional term for the total avoidable burden created when missing context, defective design, displaced authority, premature closure, or uncorrected assumptions require work to be reconstructed, reversed, repeated, escalated, cleaned up, retrained, or reverified. The word tax is intentionally metaphorical. The burden is not always centrally measured or formally collected; it is paid through fragmented time, delayed outcomes, duplicate effort, interruptions, risk, and lost trust.</p>
<div class="tableWrap"><table><tbody><tr><th>Rework channel</th><th>Typical visible activity</th><th>Continuity defect beneath it</th></tr><tr><td>Reconstruction</td><td>Searching email, interviewing veterans, rebuilding timelines</td><td>Rationale, source, or state history was not carried</td></tr><tr><td>Escalation</td><td>Meetings, approvals, handoffs, exception committees</td><td>Authority or completion boundary is unclear</td></tr><tr><td>Reversal</td><td>Undoing changes, restoring backups, correcting records</td><td>Before-state, assumptions, or verification was missing</td></tr><tr><td>Duplicate analysis</td><td>Multiple teams answer the same question independently</td><td>No inspectable decision or source lineage exists</td></tr><tr><td>Reverification</td><td>Audits repeat tests whose evidence cannot be trusted</td><td>Receipt scope or evidence class is unclear</td></tr><tr><td>Training repair</td><td>Workers learn local workarounds after formal training fails</td><td>Executed workflow diverges from documented workflow</td></tr><tr><td>Downstream remediation</td><td>Compensation, cleanup, incident response, customer recovery</td><td>A defective decision propagated before challenge or stop</td></tr></tbody></table></div>
<div class="tableWrap"><table><tbody><tr><th>CLAIM BOUNDARY Rework is not automatically waste. Iteration, experimentation, learning, redundancy, and review can be productive. The research problem is to distinguish productive iteration from avoidable reconstruction created by a preventable continuity defect, and to avoid double counting distributed costs.</th></tr></tbody></table></div>
<h3>1.4 Bureaucracy as normalized rework architecture</h3>
<p>A stronger and lower-confidence hypothesis is that some institutions may become structurally dependent on recurring rework. Reconstruction, escalation, reporting, exception handling, and blame transfer can stabilize as job functions rather than remain temporary responses to repairable defects. The hypothesis does not claim that all bureaucracy is wasteful or that governance itself is a defect. Many controls exist because consequences, rights, public accountability, and coordination are real. The challenge is to detect when a control no longer reduces risk but survives because the institution has organized people, incentives, metrics, or authority around the rework it creates.</p>
<p>Normalization of deviance literature offers an adjacent warning: repeated success in the presence of anomalies can cause a system to redefine the anomaly as acceptable. Continuity loss can create a parallel process. When the reason for a workaround disappears, the workaround may remain. When each exception is resolved locally, the recurring architecture may become invisible. Working backward from the surviving procedure - asking what failure, constraint, or fear originally made it rational - is therefore a practical research method, not proof that the procedure is obsolete.</p>
<h3>1.5 Why agents change the risk</h3>
<p>Agents do not create institutional forgetting, but they can accelerate its consequences. A human may encounter a stale rule intermittently and improvise around it. An agent can retrieve the rule, apply it consistently, call tools, update records, trigger downstream workflows, and repeat the action at scale before the lost assumption is noticed. Speed compresses the time available for informal correction. Consistency can make a wrong rule look authoritative. Tool access can convert interpretation into state change. Multi-agent handoffs can multiply the number of seams at which meaning, authority, or completion drifts.</p>
<p>The relevant distinction is not human good, machine bad. Humans also forget, rationalize, exceed authority, and normalize workarounds. The architectural claim is narrower: when automation increases execution speed, reach, and repeatability, a system should increase the quality of preserved context, authority binding, stop conditions, and receipts rather than relying on slower human friction to catch defects.</p>
<h2>The Constitutional Architecture</h2>
<h3>2.1 Canonical definition</h3>
<div class="tableWrap"><table><tbody><tr><th>LOCKED DEFINITION Continuity Calculus is the formal NULLWORKS method for preserving data, meaning, context, authority, operational state, and verification as work is transformed and passed between humans, AI workers, tools, nodes, and institutions.</th></tr></tbody></table></div>
<p>The adjective constitutional does not mean that every implementation resembles public law. It means the architecture specifies non-negotiable relationships among capability, authority, evidence, state, correction, and human control. An implementation can use JSON, databases, paper forms, signed messages, event logs, workflow engines, or human review, but it does not satisfy the method merely by storing a payload or adding an audit log.</p>
<h3>2.2 The Continuity Packet</h3>
<div class="tableWrap"><table><tbody><tr><th>CP_t = &lt;D_t, M_t, C_t, A_t, S_t, V_t&gt; Canonical six-dimensional handoff object at time t.</th></tr></tbody></table></div>
<p>D represents data and transport; M, meaning and semantics; C, context and intent; A, authority and constraints; S, operational state and transition; and V, verification and receipt. The vector notation is a compact schema, not a claim that the dimensions are independent, continuous, or mathematically complete. In practice they interact. Authority determines which context may be disclosed. Meaning affects whether a state transition is valid. Verification depends on the completion definition. A receipt can prove that bytes were signed while leaving the semantic interpretation wrong.</p>
<p class="figureCaption"><em>Figure 1. The six constitutional layers of a Continuity Packet.</em></p>
<div class="tableWrap"><table><tbody><tr><th>Layer</th><th>Controlling question</th><th>Minimum evidence</th><th>Typical failure</th></tr><tr><td>D - Transport integrity</td><td>Did the payload arrive accurately?</td><td>Hashes, sender/receiver identity, sequence, time, canonical representation, replay checks</td><td>Corruption, loss, duplication, replay, attachment mismatch</td></tr><tr><td>M - Semantic identity</td><td>What does it mean here?</td><td>Canonical terms, definitions, representation, ambiguity, unit and modality labels</td><td>Lexical drift, label collision, image substituted for live system</td></tr><tr><td>C - Contextual continuity</td><td>What history, intent, and constraints matter?</td><td>Mission, assumptions, prior decisions, failures, unknowns, corrections, freshness</td><td>Stale context, missing why, salient detail replacing objective</td></tr><tr><td>A - Constitutional authority</td><td>Who may interpret, decide, execute, stop, or escalate?</td><td>Jurisdiction, delegation, prohibitions, consequence owner, expiry, stop rule</td><td>Capability treated as permission, remote evidence forcing local decision</td></tr><tr><td>S - Operational state transition</td><td>What may legitimately change?</td><td>Before-state, preconditions, requested action, completion definition, after-state, next owner</td><td>False completion, state mutation without preconditions, orphaned handoff</td></tr><tr><td>V - Assurance and verification</td><td>What supports the interpretation and result?</td><td>Sources, evidence class, tests, reviewer class, receipts, correction lineage</td><td>Self-audit called independent, green check with wrong tests, proof scope inflation</td></tr></tbody></table></div>
<h3>2.3 Valid transformation and declared mutation</h3>
<div class="tableWrap"><table><tbody><tr><th>T_k(CP_t) -&gt; CP_(t+1) + R_k T_k is a bounded transformation; R_k is the append-only receipt describing source, declared mutations, authority, checks, and resulting state.</th></tr></tbody></table></div>
<p>A valid transformation need not preserve every field unchanged. Translation changes representation. Summarization changes detail. Redaction removes disclosed content. A policy decision changes effective state. What the method prohibits is silent material mutation: changing a term, assumption, authority, completion standard, source claim, or state while preserving the appearance of continuity. The receipt must distinguish inherited fields, transformed fields, omitted fields, inferred fields, disputed fields, and newly authorized fields.</p>
`;