"use client";
import CommercialThemeToggle from "../components/CommercialThemeToggle";
const offers=[
["Architecture Signal Scan","Starting at $7,500","Focused architecture and evidence diagnosis for systems with meaningful but bounded assurance questions."],
["Operational Assurance Sprint","$20,000-$35,000","Claim-to-control review, test mapping, authority and evidence analysis, remediation priorities, and findings receipt."],
["Full Operational Pressure Test","$50,000-$125,000+","High-consequence operational testing, independent challenge, failure-path examination, evidence custody, and retest receipts."]
];
const css=`:root,html[data-nw-theme="light"]{color-scheme:light;--p:#fff9eb;--i:#091b2c;--t:#252a2f;--m:#656965;--g:#a77b2e;--b:#d6c7a7;--c:#fffdf6;--green:#174b39;--nw-border:#d6c7a7;--nw-card:#fffdf6;--nw-text:#252a2f;--nw-shadow:none;--nw-ink:#091b2c;--nw-paper:#fff9eb}html[data-nw-theme="dark"]{color-scheme:dark;--p:#0b1118;--i:#f5ead5;--t:#f5ead5;--m:#b9c0c8;--g:#d2a85b;--b:#45515b;--c:#17212a;--green:#7fd5ad;--nw-border:#45515b;--nw-card:#17212a;--nw-text:#f5ead5;--nw-shadow:none;--nw-ink:#f5ead5;--nw-paper:#0b1118}*{box-sizing:border-box}body{margin:0;background:var(--p)!important;color:var(--t)!important;font-family:Inter,Arial,sans-serif}.page{min-height:100vh;padding:35px 0 130px;background:var(--p)!important;color:var(--t)!important}.wrap{width:min(1050px,calc(100% - 34px));margin:auto}.top{display:flex;justify-content:space-between;align-items:center;gap:15px;padding-bottom:24px;border-bottom:1px solid var(--b)}.brand{color:var(--i)!important;font-weight:950}.ey{color:var(--g)!important;font-size:12px;font-weight:900;letter-spacing:.16em;text-transform:uppercase;margin-top:35px}h1,h2{font-family:Georgia,serif;color:var(--i)!important}h1{font-size:clamp(52px,9vw,90px);line-height:.92;margin:18px 0}.lead{max-width:790px;color:var(--m)!important;font-size:19px;line-height:1.6}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px;margin-top:40px}.card{border:1px solid var(--b)!important;border-radius:24px;background:var(--c)!important;padding:25px;color:var(--t)!important}.price{color:var(--green)!important;font-size:28px;font-weight:950}.card h2{font-size:28px}.card p{color:var(--m)!important;line-height:1.6}.note{margin-top:28px;padding:18px;border-left:4px solid var(--g);background:var(--c)!important;color:var(--m)!important}.link{display:inline-flex;margin-top:28px;padding:12px 17px;border:1px solid var(--g);border-radius:999px;color:var(--i)!important;text-decoration:none;font-weight:900;background:var(--c)}@media(max-width:760px){.grid{grid-template-columns:1fr}.top{align-items:flex-start}}`;
export default function Pricing(){return <main className="page"><style dangerouslySetInnerHTML={{__html:css}}/><div className="wrap"><div className="top"><div className="brand">NULLWORKS / PRICING</div><CommercialThemeToggle/></div><div className="ey">OPERATIONAL ASSURANCE</div><h1>Operational assurance pricing.</h1><p className="lead">Published ranges make the commercial boundary visible before a conversation starts. Final scope depends on system consequence, evidence availability, access, and the testing required.</p><div className="grid">{offers.map(([n,p,d])=><article className="card" key={n}><div className="price">{p}</div><h2>{n}</h2><p>{d}</p></article>)}</div><div className="note">Triage is the starting point. It exists to avoid selling a giant engagement when a smaller diagnostic is enough, because apparently restraint can also be a business model.</div><a className="link" href="/triage">Run Triage</a></div></main>}
