import type { Metadata } from "next";
export const metadata:Metadata={title:"Operational Assurance Pricing | NULLWORKS"};
const offers=[
["Architecture Signal Scan","Starting at $7,500","Focused architecture and evidence diagnosis for systems with meaningful but bounded assurance questions."],
["Operational Assurance Sprint","$20,000-$35,000","Claim-to-control review, test mapping, authority and evidence analysis, remediation priorities, and findings receipt."],
["Full Operational Pressure Test","$50,000-$125,000+","High-consequence operational testing, independent challenge, failure-path examination, evidence custody, and retest receipts."]
];
const css=`*{box-sizing:border-box}body{margin:0;background:#0b1118!important;color:#f5ead5!important;font-family:Inter,Arial,sans-serif}.page{min-height:100vh;padding:65px 0 130px}.wrap{width:min(1050px,calc(100% - 34px));margin:auto}.ey{color:#d2a85b;font-size:12px;font-weight:900;letter-spacing:.16em;text-transform:uppercase}h1,h2{font-family:Georgia,serif}h1{font-size:clamp(52px,9vw,90px);line-height:.92;margin:18px 0}.lead{max-width:790px;color:#b9c0c8;font-size:19px;line-height:1.6}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px;margin-top:40px}.card{border:1px solid #45515b;border-radius:24px;background:#17212a;padding:25px}.price{color:#7fd5ad;font-size:28px;font-weight:950}.card h2{font-size:28px}.card p{color:#b9c0c8;line-height:1.6}.note{margin-top:28px;padding:18px;border-left:4px solid #d2a85b;background:#151e27;color:#c5c8c9}.link{display:inline-flex;margin-top:28px;padding:12px 17px;border:1px solid #d2a85b;border-radius:999px;color:#f5ead5;text-decoration:none;font-weight:900}@media(max-width:760px){.grid{grid-template-columns:1fr}}`;
export default function Pricing(){return <main className="page"><style dangerouslySetInnerHTML={{__html:css}}/><div className="wrap"><div className="ey">NULLWORKS / PRICING</div><h1>Operational assurance pricing.</h1><p className="lead">Published ranges make the commercial boundary visible before a conversation starts. Final scope depends on system consequence, evidence availability, access, and the testing required.</p><div className="grid">{offers.map(([n,p,d])=><article className="card" key={n}><div className="price">{p}</div><h2>{n}</h2><p>{d}</p></article>)}</div><div className="note">Triage is the starting point. It exists to avoid selling a giant engagement when a smaller diagnostic is enough, because apparently restraint can also be a business model.</div><a className="link" href="/triage">Run Triage</a></div></main>}
