import type { Metadata } from "next";
import Link from "next/link";
import styles from "./japan.module.css";

export const metadata: Metadata = {
  title: "Japan Partnerships | NULLWORKS",
  description: "Experimental AI, robotics and space systems, and operational wisdom mining developed with Japanese partners.",
  alternates: { canonical: "https://nullworks.systems/japan" },
};

const lanes = [
  { number: "01", title: "Experimental AI systems", thesis: "Architect, generate, integrate, and pressure-test AI software while preserving human authority, telemetry, provenance, and reconstructable decisions.", japan: "A bounded co-development project around one industrial, regulated, infrastructure, inspection, or logistics workflow selected with the Japanese partner.", partner: "AI developer · operator · regulated enterprise · research institution", evidence: [["UMBRA + PENUMBRA architecture", "/architecture", "PUBLISHED ARCHITECTURE"], ["AI Operating Model Audit", "/ai-audit/intake", "WORKING SYSTEM"], ["Targeted AI assurance", "/ciris-proof", "FIELD EVIDENCE"]] },
  { number: "02", title: "Robotics + space systems", thesis: "Build the software and control architecture around robots, cameras, sensors, smart glasses, remote observation, maintenance, and future autonomous infrastructure.", japan: "Begin on Earth with a measurable robotics or machine-vision problem. Lunar infrastructure is the long-horizon trajectory—not the first procurement request.", partner: "Robotics maker · machine-vision team · physical operator · university · space participant", evidence: [["PMAR operational robotics", "/pmar", "FIELD EVIDENCE"], ["Remote Eye observation system", "/remote-eye-v3/", "WORKING SYSTEM"], ["Operation Moonshot", "/operation-moonshot/industrial-bootstrap", "RESEARCH CONCEPT"]] },
  { number: "03", title: "Wisdom + knowledge mining", thesis: "Preserve expert reasoning, exceptions, failure history, language, and judgment before retirement or organizational change makes them impossible to rebuild.", japan: "A voluntary, source-attributed pilot with expert review, correction rights, and a transfer test: can another person use the captured knowledge correctly?", partner: "Manufacturer · regional institution · university · archive · long-lived enterprise", evidence: [["Operational Wisdom Mining", "/wisdom-mining", "PUBLISHED ARCHITECTURE"], ["The knowledge we cannot rebuild", "/field-notes/the-knowledge-we-cannot-rebuild", "RESEARCH CONCEPT"], ["First field evidence", "/field-notes/kikigaki-first-nugget", "FIELD EVIDENCE"]] },
] as const;

export default function JapanPage() {
  return <main className={styles.page}>
    <nav className={styles.nav}><Link className={styles.brand} href="/">NULLWORKS <span>JAPAN</span></Link><div><Link href="/architecture">Architecture</Link><Link href="/proof">Proof</Link><Link href="/company">Company</Link></div></nav>
    <header className={styles.hero}><div><p className={styles.eyebrow}>JAPAN · PARTNERSHIP ROUTE</p><h1>Experimental systems built with Japanese partners.</h1><p className={styles.lead}>AI is the first capability. Robotics connects it to the physical world. Space is the frontier trajectory. Wisdom mining preserves the human knowledge those systems must not erase.</p><div className={styles.actions}><a href="#programs">Explore the three programs</a><a href="mailto:nullworks.neuraxis@gmail.com?subject=NULLWORKS%20Japan%20partnership">Discuss a Japanese partnership</a></div></div><aside className={styles.mission}><span>THE FIRST MISSION</span><strong>One partner.<br/>One operating problem.<br/>One bounded experiment.<br/>One measurable result.</strong><p>NULLWORKS is not proposing monetary policy, a finished universal robot, or a way to strengthen the yen.</p></aside></header>
    <section className={styles.intro}><p className={styles.eyebrow}>WHY JAPAN</p><h2>Deep capability. Real constraints. Long-horizon partners.</h2><p>Japan combines industrial depth, robotics leadership, infrastructure discipline, demographic pressure, regional revitalization needs, and growing investment in AI and space. NULLWORKS is seeking collaborators who can supply the real operating environment, domain knowledge, and requirements that experimental systems need.</p></section>
    <section id="programs" className={styles.lanes}>{lanes.map((lane) => <article className={styles.lane} key={lane.number}><div className={styles.laneHead}><span>{lane.number}</span><h2>{lane.title}</h2></div><p className={styles.thesis}>{lane.thesis}</p><div className={styles.details}><div><b>WHAT WE WANT TO DO IN JAPAN</b><p>{lane.japan}</p></div><div><b>PARTNER FIT</b><p>{lane.partner}</p></div></div><div className={styles.evidence}><b>EXISTING EVIDENCE</b>{lane.evidence.map(([label, href, status]) => <Link href={href} key={href}><span>{label}</span><small>{status}</small></Link>)}</div></article>)}</section>
    <section className={styles.pilot}><div><p className={styles.eyebrow}>BOUNDED PROOF OF CONCEPT</p><h2>Ninety days to learn something real.</h2></div><ol><li><b>01</b><span>Choose one consequential workflow</span></li><li><b>02</b><span>Map actors, evidence, authority, and failure cost</span></li><li><b>03</b><span>Build the smallest useful intervention</span></li><li><b>04</b><span>Pressure-test with domain experts</span></li><li><b>05</b><span>Issue a reconstructable evidence receipt</span></li></ol></section>
    <section className={styles.jetro}><div><p className={styles.eyebrow}>WHERE JETRO FITS</p><h2>Connections before transactions.</h2><p>J-Bridge can help identify a Japanese co-development partner. Invest Japan can help NULLWORKS understand market entry and the institutional landscape. Regional offices can connect a specific capability to a specific local need.</p></div><aside><b>THE REQUEST TO RYO</b><p>Help us find one experimental AI or robotics partner, one physical-operations organization with a measurable problem, and one institution facing expert-knowledge loss.</p><a href="mailto:nullworks.neuraxis@gmail.com?subject=NULLWORKS%20Japan%20partnership">nullworks.neuraxis@gmail.com →</a></aside></section>
    <footer><Link href="/">← NULLWORKS</Link><span>Arizona · United States · Japan partnership route</span></footer>
  </main>;
}
