import type { Metadata } from "next";
import Link from "next/link";
import styles from "./japan.module.css";

export const metadata: Metadata = {
  title: "NULLWORKS Japan | Experimental AI, Robotics, Space & Knowledge Continuity",
  description: "NULLWORKS Japan partnership hub for experimental AI, robotics and physical systems, space research, and wisdom and knowledge mining.",
  alternates: { canonical: "https://nullworks.systems/japan" },
};

const lanes = [
  { number: "01", title: "Experimental AI systems", thesis: "Architect, generate, integrate, and pressure-test AI software while preserving human authority, telemetry, provenance, and reconstructable decisions.", japan: "Co-develop one bounded system around a real industrial, regulated, infrastructure, inspection, logistics, or physical-operations workflow. The point is not another demonstration chatbot. It is evidence about what happens when AI is allowed to participate in consequential work.", partner: "AI developer · industrial operator · regulated enterprise · research institution · regional innovation organization", evidence: [["UMBRA + PENUMBRA architecture", "/architecture", "PUBLISHED ARCHITECTURE"], ["AI Operating Model Audit", "/ai-audit/intake", "WORKING SYSTEM"], ["Targeted AI assurance", "/ciris-proof", "FIELD EVIDENCE"]] },
  { number: "02", title: "Robotics + physical systems", thesis: "Connect intelligence to robots, cameras, sensors, smart glasses, remote observation, inspection, maintenance, logistics, and other systems that touch the physical world.", japan: "Begin with a terrestrial problem whose outcome can be measured: machine vision, remote inspection, maintenance, logistics, emergency response, field observation, or another bounded physical workflow. Governance matters more when software can act on machinery and infrastructure.", partner: "Robotics manufacturer · machine-vision developer · maintenance operator · logistics operator · emergency-services technology team · university laboratory", evidence: [["PMAR operational robotics", "/pmar", "FIELD EVIDENCE"], ["Remote Eye observation system", "/remote-eye-v3/", "WORKING SYSTEM"], ["Operation Moonshot", "/operation-moonshot/industrial-bootstrap", "RESEARCH CONCEPT · SPACE TRAJECTORY"]] },
  { number: "03", title: "Wisdom + knowledge mining", thesis: "Preserve expert reasoning, exceptions, failure history, language, judgment, and teaching stories before retirement or organizational change makes that knowledge impossible to rebuild.", japan: "Run a voluntary, source-attributed knowledge-continuity pilot with expert review, correction rights, provenance, and a transfer test: can another person correctly use what was preserved? The aim is to extend expertise, not erase the expert.", partner: "Manufacturer · long-lived enterprise · regional institution · university · archive · trade or professional association", evidence: [["Operational Wisdom Mining", "/wisdom-mining", "PUBLISHED ARCHITECTURE"], ["The knowledge we cannot rebuild", "/field-notes/the-knowledge-we-cannot-rebuild", "RESEARCH CONCEPT"], ["First Kikigaki field evidence", "/field-notes/kikigaki-first-nugget", "FIELD EVIDENCE"]] },
] as const;

export default function JapanPage() {
  return <main className={styles.page}>
    <nav className={styles.nav}><Link className={styles.brand} href="/">NULLWORKS <span>JAPAN</span></Link><div><Link href="/architecture">Architecture</Link><Link href="/products">Systems</Link><Link href="/proof">Proof</Link><Link href="/research">Research</Link><Link href="/company">Company</Link></div></nav>
    <header className={styles.hero}><div><p className={styles.eyebrow}>NULLWORKS JAPAN · PARTNERSHIP + CO-DEVELOPMENT</p><h1>Experimental systems built with Japanese partners.</h1><p className={styles.lead}>AI is the front door. Robotics connects intelligence to the physical world. Space is the frontier trajectory. Wisdom mining preserves the human knowledge those systems must not erase. Underneath all four is governed architecture that keeps capability connected to human authority, evidence, provenance, safe execution, and verification.</p><div className={styles.actions}><a href="#programs">Explore the collaboration lanes</a><a href="mailto:nullworks.neuraxis@gmail.com?subject=NULLWORKS%20Japan%20partnership">Discuss a Japanese partnership</a></div></div><aside className={styles.mission}><span>THE FIRST MISSION</span><strong>One partner.<br/>One operating problem.<br/>One bounded experiment.<br/>One measurable result.</strong><p>Connections before transactions. Start small enough to measure honestly, preserve the evidence, then scale only when the result earns it.</p></aside></header>
    <section className={styles.intro}><p className={styles.eyebrow}>WHY JAPAN</p><h2>Deep capability. Real constraints. Long-horizon partners.</h2><p>Japan combines industrial depth, robotics, infrastructure discipline, demographic pressure, regional revitalization needs, and serious AI and space ambitions. That combination creates unusually valuable ground for systems that join new machine capability with operational evidence and human judgment. NULLWORKS is looking for Japanese organizations that can bring the real environment, domain expertise, constraints, and hard problems required to make experimental systems useful.</p></section>
    <section id="programs" className={styles.lanes}>{lanes.map((lane) => <article className={styles.lane} key={lane.number}><div className={styles.laneHead}><span>{lane.number}</span><h2>{lane.title}</h2></div><p className={styles.thesis}>{lane.thesis}</p><div className={styles.details}><div><b>WHAT WE WANT TO DO IN JAPAN</b><p>{lane.japan}</p></div><div><b>PARTNER FIT</b><p>{lane.partner}</p></div></div><div className={styles.evidence}><b>EXISTING EVIDENCE</b>{lane.evidence.map(([label, href, status]) => <Link href={href} key={href}><span>{label}</span><small>{status}</small></Link>)}</div></article>)}</section>
    <section className={styles.architecture}><p className={styles.eyebrow}>THE SHARED ARCHITECTURE</p><h2>Different experiments. One governed operating model underneath them.</h2><p>NULLWORKS does not sell intelligence. NULLWORKS builds the architecture through which intelligence is permitted to interact with systems. The same operating principles can govern an AI workflow, a camera, a robot, a maintenance system, or a future autonomous infrastructure layer without requiring one model, manufacturer, or software vendor.</p><div className={styles.architectureGrid}><Link href="/architecture"><b>UMBRA</b><small>Governed execution and control architecture.</small></Link><Link href="/architecture"><b>PENUMBRA</b><small>Human-facing interaction and authority layer.</small></Link><Link href="/continuity-calculus"><b>CONTINUITY CALCULUS</b><small>Preserving valid identity, authority, context, and succession as systems change.</small></Link><Link href="/proof"><b>EVIDENCE + RECEIPTS</b><small>Reconstructable proof of what was authorized, tested, changed, and verified.</small></Link></div></section>
    <section className={styles.pilot}><div><p className={styles.eyebrow}>BOUNDED PROOF OF CONCEPT</p><h2>Approximately ninety days to learn something real.</h2><p className={styles.thesis}>The exact duration follows the problem. The discipline does not: define the boundary, expose the smallest useful capability, measure what happened, and preserve enough evidence that somebody else can reconstruct the result.</p></div><ol><li><b>01</b><span>Choose one consequential workflow and measurable outcome</span></li><li><b>02</b><span>Map actors, evidence, authority, constraints, exceptions, and failure cost</span></li><li><b>03</b><span>Build the smallest useful intervention</span></li><li><b>04</b><span>Pressure-test it with domain experts in the real operating context</span></li><li><b>05</b><span>Verify the result and issue a reconstructable evidence receipt</span></li></ol></section>
    <section className={styles.jetro}><div><p className={styles.eyebrow}>JETRO + JAPANESE PARTNERSHIP ROUTING</p><h2>Connections before transactions.</h2><p>JETRO is one pathway into the larger Japan program, not its boundary. J-Bridge may help identify Japanese co-development relationships; Invest Japan can help NULLWORKS understand market-entry and institutional requirements; regional connections may help match a specific capability to a specific local need. Any support, introduction, or program participation remains subject to what JETRO actually confirms.</p></div><aside><b>THE INITIAL REQUEST</b><p>Help identify one experimental-AI or robotics co-development partner, one physical-operations organization with a measurable problem, and one institution facing serious expert-knowledge loss.</p><a href="mailto:nullworks.neuraxis@gmail.com?subject=NULLWORKS%20Japan%20partnership">nullworks.neuraxis@gmail.com →</a></aside></section>
    <footer><Link href="/">← NULLWORKS</Link><span>Arizona · United States · Japan partnership route</span></footer>
  </main>;
}
