import type { Metadata } from "next";
import Link from "next/link";
import styles from "../corporate.module.css";

export const metadata: Metadata = { title: "PMAR | NULLWORKS", description: "PMAR is a NULLWORKS field system for persistent physical-asset identity, maintenance state, and scan-to-record operations.", alternates:{canonical:"https://nullworks.systems/pmar"} };

export default function PMARPage(){return <main className={styles.page}><div className={styles.shell}>
<nav className={styles.nav}><Link className={styles.brand} href="/">NULLWORKS<span>FIELD EVIDENCE · PHYSICAL OPERATIONS</span></Link><div className={styles.mono}>PMAR</div></nav>
<section className={styles.compactHero}><div className={styles.eyebrow}>PERSISTENT MAINTENANCE + ASSET RECORD</div><h1 className={styles.title}>The marker is the address. The record is the identity.</h1><p className={styles.lead}>PMAR connects a durable physical marker to a persistent operational record so equipment, locations, inspections, service history, observations, and future automation can refer to the same thing over time.</p><div className={styles.actions}><Link className={styles.primary} href="/japan">Japan program</Link><Link className={styles.secondary} href="/architecture">Governed architecture</Link></div></section>
<section className={styles.section}><div className={styles.sectionHeader}><div className={styles.kicker}>THE OPERATING PROBLEM</div><h2 className={styles.h2}>Physical systems lose context between people, shifts, paper, software, and time.</h2><p className={styles.body}>A machine can have a serial number, a local nickname, handwritten service notes, meter hours, parts history, operator knowledge, and a database record that never quite agree. PMAR starts by giving the physical thing a stable point of reference. Scan the marker and the current record follows the asset instead of forcing the worker to hunt for the system that contains it.</p></div><div className={styles.list}><div className={styles.item}><strong>Persistent identity</strong><span>The physical marker resolves to a durable record rather than encoding the entire changing record in the label.</span></div><div className={styles.item}><strong>Operational state</strong><span>Status, hours, last service, observations, maintenance needs, and supporting evidence can accumulate around the same identity.</span></div><div className={styles.item}><strong>Field-first interaction</strong><span>The worker begins with the thing in front of them: find the marker, scan it, see or update the relevant record.</span></div><div className={styles.item}><strong>Future machine participation</strong><span>The same stable identity can later be referenced by cameras, sensors, robots, maintenance agents, or governed AI without inventing a new identity layer for every device.</span></div></div></section>
<section className={styles.section}><div className={styles.statement}><strong>FIELD EVIDENCE, NOT A PRODUCT CLAIM</strong><p>PMAR has been exercised as a working field prototype around maintenance and physical equipment. The current public page describes the architecture and observed workflow. It does not claim a certified production deployment, manufacturer integration, or affiliation with equipment manufacturers.</p></div></section>
<section className={styles.section}><div className={styles.sectionHeader}><div className={styles.kicker}>WHY IT MATTERS TO JAPAN</div><h2 className={styles.h2}>A small identity primitive can connect maintenance, robotics, inspection, and knowledge continuity.</h2><p className={styles.body}>In a Japanese co-development setting, the useful experiment is deliberately bounded: choose one class of equipment or one physical workflow, establish persistent identity, capture the evidence people already use, then test whether maintenance personnel or machine systems can act with less ambiguity and better reconstructability.</p></div></section>
<footer className={styles.footer}><span>NULLWORKS · PMAR · FIELD EVIDENCE</span><Link className={styles.route} href="/japan">Return to Japan program →</Link></footer>
</div></main>}
