"use client";
import CommercialThemeToggle from "../components/CommercialThemeToggle";

type Status="Verified"|"Publicly described"|"Partially described"|"Unknown / not publicly evidenced";
const rows:[string,Status,Status,Status,Status][]=[
["Human authority / jurisdiction","Verified","Publicly described","Publicly described","Publicly described"],
["Evidence and decision lineage","Verified","Partially described","Partially described","Partially described"],
["Correction / supersession path","Verified","Partially described","Unknown / not publicly evidenced","Unknown / not publicly evidenced"],
["Claim-to-test mapping","Verified","Partially described","Partially described","Partially described"],
["Independent reproduction receipts","Verified","Unknown / not publicly evidenced","Unknown / not publicly evidenced","Unknown / not publicly evidenced"],
["Completion semantics","Verified","Partially described","Partially described","Partially described"],
["Version-pinned public assurance proof","Verified","Unknown / not publicly evidenced","Unknown / not publicly evidenced","Unknown / not publicly evidenced"]
];
const styles=`:root,html[data-nw-theme="light"]{color-scheme:light;--p:#fff9eb;--p2:#f3e7cf;--i:#091b2c;--t:#252a2f;--m:#656965;--g:#a77b2e;--b:#d6c7a7;--c:#fffdf6;--nw-border:#d6c7a7;--nw-toggle-bg:rgba(255,255,255,.72);--nw-ink:#091b2c;--nw-paper:#fff9eb;--nw-muted:#656965;--nw-gold:#a77b2e}html[data-nw-theme="dark"]{color-scheme:dark;--p:#111821;--p2:#18232d;--i:#f5ead5;--t:#f1eee7;--m:#bab8b2;--g:#d2a85b;--b:#3b4650;--c:#17212a;--nw-border:#3b4650;--nw-toggle-bg:rgba(17,24,33,.82);--nw-ink:#f5ead5;--nw-paper:#111821;--nw-muted:#bab8b2;--nw-gold:#d2a85b}*{box-sizing:border-box}body{margin:0;background:var(--p)!important;color:var(--t)!important;font-family:Inter,Arial,sans-serif}.shell{width:min(1120px,calc(100% - 28px));margin:auto;padding-bottom:70px}nav{display:flex;justify-content:space-between;gap:16px;align-items:center;padding:18px 0;border-bottom:1px solid var(--b)}nav a{color:var(--i);font-weight:950;text-decoration:none;letter-spacing:.08em}header{padding:58px 0 36px}.ey{color:var(--g);font-size:11px;font-weight:950;letter-spacing:.15em;text-transform:uppercase}h1,h2{font-family:Georgia,serif;color:var(--i);letter-spacing:-.04em}h1{font-size:clamp(48px,8vw,88px);line-height:.9;margin:16px 0}.lead{max-width:850px;font-size:19px;line-height:1.6;color:var(--m)}.truth{padding:15px 17px;border-left:4px solid var(--g);background:var(--c);color:var(--m)}section{padding:42px 0;border-top:1px solid var(--b)}h2{font-size:38px}.legend{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.pill,.s{display:inline-block;border-radius:999px;padding:6px 9px;font-size:11px;font-weight:900;border:1px solid var(--b)}.Verified{background:#dff3e8;color:#174b39}.Publicly{background:#e6edf6;color:#183b62}.Partially{background:#f7ebca;color:#6e4a08}.Unknown{background:#eeeae2;color:#5e5d59}html[data-nw-theme="dark"] .Verified{background:#17382e;color:#9ce2c3}html[data-nw-theme="dark"] .Publicly{background:#172f49;color:#acd1f5}html[data-nw-theme="dark"] .Partially{background:#443615;color:#f0cc76}html[data-nw-theme="dark"] .Unknown{background:#30353a;color:#d2d0ca}.tablewrap{overflow:auto;border:1px solid var(--b);border-radius:18px;background:var(--c)}table{width:100%;border-collapse:collapse;min-width:800px}th,td{text-align:left;padding:15px;border-bottom:1px solid var(--b);vertical-align:top}th{color:var(--i);font-size:12px}td:first-child{font-weight:800;color:var(--i)}.proof{display:grid;grid-template-columns:1.4fr .6fr;gap:16px}.card{border:1px solid var(--b);border-radius:18px;background:var(--c);padding:22px}.card p{color:var(--m);line-height:1.6}.btn{display:inline-flex;padding:11px 15px;border-radius:999px;background:var(--i);color:var(--p)!important;text-decoration:none;font-weight:900;margin:4px 6px 4px 0}@media(max-width:700px){.proof{grid-template-columns:1fr}nav{align-items:flex-start}h1{font-size:52px}}`;
const cls=(s:Status)=>s.split(" ")[0].replace("/","");
export default function AssuranceMatrix(){return <main><style dangerouslySetInnerHTML={{__html:styles}}/><div className="shell"><nav><a href="/assurance">NULLWORKS / ASSURANCE</a><CommercialThemeToggle/></nav><header><div className="ey">Public evidence matrix // August 2026</div><h1>What is actually evidenced?</h1><p className="lead">This matrix separates independently reproduced evidence from public descriptions and unknowns. A blank public record is not treated as a product failure. It is treated as an unknown.</p><div className="truth">This is an evidence-availability comparison, not a product ranking, certification table, security score, or claim that NULLWORKS has inspected non-CIRIS proprietary systems.</div></header><section><h2>Evidence status</h2><div className="legend">{(["Verified","Publicly described","Partially described","Unknown / not publicly evidenced"] as Status[]).map(x=><span className={`pill ${cls(x)}`} key={x}>{x}</span>)}</div><div className="tablewrap"><table><thead><tr><th>Assurance dimension</th><th>CIRISAgent pinned review</th><th>OpenAI public materials</th><th>Anthropic public materials</th><th>Google public materials</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}>{r.map((v,i)=>i===0?<td key={v}>{v}</td>:<td key={`${r[0]}-${i}`}><span className={`s ${cls(v as Status)}`}>{v}</span></td>)}</tr>)}</tbody></table></div><p className="lead" style={{fontSize:14}}>Large vendors publish substantial safety, security, model, and governance material. This table intentionally asks a narrower operational-assurance question: what evidence is publicly available at the specific claim → control → test → receipt level used by this NULLWORKS review method?</p></section><section id="currently-assured"><h2>Currently assured software</h2><div className="proof"><div className="card"><div className="ey">Independent public proof available</div><h2 style={{fontSize:32}}>CIRISAgent</h2><p>Source-pinned operational assurance review of CIRISAgent and CIRISPersist. The public proof records 42/42 selected project tests, 10/10 deterministic source-conformance checks, and 3/3 preregistered direct authorization calls, with explicit limits on what is claimed.</p><a className="btn" href="https://github.com/masoncalcolsol-creator/mason-portfolio/blob/main/public-proof/CIRIS_ASSURANCE_PUBLIC_PROOF.md" target="_blank" rel="noreferrer">Open CIRIS public proof</a></div><div className="card"><div className="ey">Truth boundary</div><p>“Verified” here means independently reproduced within the scope of the pinned NULLWORKS review. It does not mean certified, production-observed, universally correct, or endorsed by CIRISAI.</p><a className="btn" href="/triage">Run Triage</a></div></div></section></div></main>}
